matter-labs/era-contracts

ethereum/contracts/zksync/Config.sol, ethereum/contracts/zksync/facets/Executor.sol, ethereum/scripts/deploy-erc20.ts, ethereum/scripts/utils.ts, ethereum/test/unit_tests/executor_test.spec.ts, ethereum/test/unit_tests/l2-upgrade.test.spec.ts, ethereum/test/unit_tests/utils.ts
Mirror to the most recent version:
77ef3c5583772d0431836f19cd9367d365991d72
(it is also equivalent to 5ff1252d35b95113bc1478fe966d23f1bb4b6a33 - that was a non-squashed commit on private repo).
=> mirror to both 5ff1252 and 77ef3c5

ethereum/contracts/verifier/Verifier.sol
Remove the `VK_` prefix from the trusted setup params, since these are not included in the `_loadVerificationKey()`.
=> Remove vk where unneeded

zksync/package.json
The scripts are created as 'commander' commands, and if executed with hardhat run won't accept the parameters and will throw an error. Changing to 'ts-node' executes them properly.
Merging to main - as the PR is only touching the scripts and not the contracts.
=> Fix: replaced hardhat run with ts-node

ethereum/test/unit_tests/executor_test.spec.ts
Use the hardhat provider instead of the default provider by ethers.
The default provider by ethers queries information about an external chain.
- [+] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [+] Tests for the changes have been added / updated.
- [+] Documentation comments have been added / updated.
- [+] Code has been formatted via `zk fmt` and `zk lint`.
=> Use local provider for tests

ethereum/contracts/bridge/L1WethBridge.sol
- Fix bug with incorrect inputs in withdrawal finalization function.
- Fix the bug.
=> Fix WETH bridge issue with withdrawals

docs/Overview.md
Update doc to reflect new log structure for boojum
Keep docs up to date
=> feat(docs): update docs for ExecutorFacet

ethereum/contracts/zksync/DiamondInit.sol, ethereum/package.json, ethereum/src.ts/deploy.ts, ethereum/test/unit_tests/l1_erc20_bridge_test.spec.ts, ethereum/test/unit_tests/l1_weth_bridge_test.spec.ts, ethereum/test/unit_tests/l2-upgrade.test.spec.ts, ethereum/test/unit_tests/mailbox_test.spec.ts, ethereum/test/unit_tests/proxy_test.spec.ts
- Fix coverage script for Foundry tests.
- Coverage wasn't working due to "Stack to deep" error on contracts compilation without optimisations
=> Fix foundry coverage

.github/workflows/ci.yml, zksync/hardhat.config.ts, zksync/package.json, zksync/test/weth.test.ts, zksync/yarn.lock
Unit-tests for WETH token and WETH bridge using era-test-node.
There weren't any
=> Add unit-tests for WETH token and WETH bridge

ethereum/contracts/zksync/Config.sol
Shift public input by 4 bytes
Needed for correct public input generation [here](https://github.com/matter-labs/era-contracts/blob/f06a58360a2b8e7129f64413998767ac169d1efd/ethereum/contracts/zksync/facets/Executor.sol#L396)
=> Shift public input by 4 bytes

ethereum/src.ts/deploy.ts
* depending on the CONTRACTS_PROVER_AT_GENESIS environment variable, set correct VkHashes
* later migrations of provers, happen via migration mechanism, but for boojnet and local setups, we need a way to set the prover that will be used at genesis.
* otherwise, we'd have to run the 'old' prover to prove at least one block (to do the migration).
Change is backwards compatible - if flag is not set, we'll use the old (current) setup
=> feat(boojum): Add a flag to control which prover to use at diamond init

ethereum/package.json
Removes a `test` script indirection to call hardhat directly
Otherwise `zk test l2-contracts` run from `zksync-era` fails with 
```
HardhatError: HH12: Trying to use a non-local installation of Hardhat, which is not supported.
Please install Hardhat locally using npm or Yarn, and try again.
```
=> Remove test script indirection

ethereum/contracts/common/AllowList.sol, ethereum/contracts/common/interfaces/IAllowList.sol, ethereum/test/foundry/unit/concrete/AllowList/AccessMode/DepositLimit.t.sol
Created the `UpdateDepositLimit` event and emitting it at the end of the `setDepositLimit` function.
To make deposit limit changes trackable for off-chain clients.
=> feat: add event for setDepositLimit

zksync/contracts/ForceDeployUpgrader.sol, zksync/contracts/L2ContractHelper.sol
* updated the IContractDeployer interface: made the create2 and forceDeployOnAddresses payable
* made the forceDeploy function payable
In the era-system-contracts the ContractDeployer's create2 and forceDeployOnAddresses functions are payable (https://github.com/matter-labs/era-system-contracts/blob/dev/contracts/ContractDeployer.sol), therefore updated the interface and made the forceDeploy function payable.
=> fix: add payable for forceDeploy

docs/Overview.md, ethereum/contracts/zksync/DiamondInit.sol, ethereum/src.ts/deploy.ts, ethereum/test/foundry/unit/concrete/Bridge/L1WethBridge/_L1WethBridge_Shared.t.sol, ethereum/test/foundry/unit/concrete/DiamondCut/UpgradeLogic.t.sol, ethereum/test/foundry/unit/concrete/Executor/_Executor_Shared.t.sol, ethereum/test/unit_tests/l1_erc20_bridge_test.spec.ts, ethereum/test/unit_tests/l1_weth_bridge_test.spec.ts, ethereum/test/unit_tests/l2-upgrade.test.spec.ts, ethereum/test/unit_tests/mailbox_test.spec.ts, ethereum/test/unit_tests/proxy_test.spec.ts
Add initial protocol version (as the server relies on it to be correct from the genesis)
=> Add initial protocol version

ethereum/contracts/zksync/facets/Executor.sol
Ensure that `proofPublicInput` is equal to 1, not the proof's length itself
For correctness of the execution
=> Fix block verification

zksync/hardhat.config.ts
Upgrading zksolc version to 1.3.17
Prior to 1.13.16, there is no binary available for linux-arm64 which is breaking the `zk init` or `hyperchain init` script 
https://github.com/matter-labs/zksolc-bin/tree/main/linux-arm64
=> Upgrade zksolc version to 1.3.17

l1-contracts/test/foundry/unit/concrete/UncheckedMath/UncheckedAdd.t.sol, l1-contracts/test/foundry/unit/concrete/UncheckedMath/UncheckedInc.t.sol, l1-contracts/test/foundry/unit/concrete/UncheckedMath/_UncheckedMath_Shared.t.sol
=> test: unchecked math test

ethereum/contracts/zksync/facets/Getters.sol
Fixing the comment about retrieving the latest unprocessed priority transaction
=> Fix comment for getting the latest unprocessed priority transaction

ethereum/contracts/zksync/interfaces/IAdmin.sol, ethereum/contracts/zksync/interfaces/IBase.sol, ethereum/contracts/zksync/interfaces/IExecutor.sol, ethereum/contracts/zksync/interfaces/IGetters.sol, ethereum/contracts/zksync/interfaces/ILegacyGetters.sol, ethereum/contracts/zksync/interfaces/IMailbox.sol, ethereum/contracts/zksync/interfaces/IVerifier.sol, ethereum/contracts/zksync/interfaces/IZkSync.sol
=> Include security contact

ethereum/contracts/zksync/Config.sol, ethereum/contracts/zksync/facets/Executor.sol
=> Remove unused imports

.github/workflows/buld-release.yaml, .github/workflows/l1-contracts-ci.yaml, .github/workflows/l2-contracts-ci.yaml, .github/workflows/system-contracts-ci.yaml
=> ci: prepare workflow for release contracts

ethereum/contracts/bridge/L1ERC20Bridge.sol, ethereum/contracts/bridge/L1WethBridge.sol, ethereum/contracts/upgrades/BaseZkSyncUpgrade.sol, ethereum/contracts/zksync/Config.sol, ethereum/contracts/zksync/Verifier.sol, ethereum/contracts/zksync/facets/Admin.sol, ethereum/contracts/zksync/facets/Base.sol, ethereum/contracts/zksync/facets/Executor.sol, ethereum/contracts/zksync/facets/Getters.sol, ethereum/contracts/zksync/facets/Mailbox.sol, ethereum/contracts/zksync/interfaces/IAdmin.sol, ethereum/contracts/zksync/interfaces/IBase.sol, ethereum/contracts/zksync/interfaces/IExecutor.sol, ethereum/contracts/zksync/interfaces/IGetters.sol, ethereum/contracts/zksync/interfaces/ILegacyGetters.sol, ethereum/contracts/zksync/interfaces/IMailbox.sol, ethereum/contracts/zksync/interfaces/IVerifier.sol, ethereum/contracts/zksync/interfaces/IZkSync.sol, ethereum/contracts/zksync/libraries/TransactionValidator.sol, ethereum/test/unit_tests/governance_test.spec.ts, tools/data/verifier_contract_template.txt, zksync/contracts/bridge/L2StandardERC20.sol
=> Port 1 4 1 fixes to the short term fee model

ethereum/contracts/dev-contracts/test/CustomUpgradeTest.sol, ethereum/contracts/upgrades/BaseZkSyncUpgrade.sol, ethereum/contracts/upgrades/DefaultUpgrade.sol
=> Make upgrade validation more strict

ethereum/contracts/bridge/L1ERC20Bridge.sol, ethereum/contracts/bridge/L1WethBridge.sol, ethereum/contracts/governance/Governance.sol, ethereum/contracts/zksync/Storage.sol, ethereum/contracts/zksync/libraries/Diamond.sol, ethereum/contracts/zksync/libraries/LibMap.sol, ethereum/contracts/zksync/libraries/PriorityQueue.sol, zksync/contracts/bridge/L2ERC20Bridge.sol
=> Named mapping variables

l1-contracts/foundry.toml
I've found an outdated link pointing to foundry config documentation. This PR replaces the outdated link with a working link.
To keep external resources approachable.
=> fix: outdated link to foundry config docs

l1-contracts/contracts/zksync/interfaces/IExecutor.sol, system-contracts/contracts/L1Messenger.sol, system-contracts/contracts/interfaces/IPubdataChunkPublisher.sol
=> chore(docstrings): added doc string comments where missing

l1-contracts/contracts/zksync/Config.sol, l1-contracts/contracts/zksync/facets/Executor.sol, l1-contracts/contracts/zksync/utils/BlobVersionedHash.yul, system-contracts/bootloader/bootloader.yul, system-contracts/contracts/Constants.sol, system-contracts/contracts/PubdataChunkPublisher.sol
=> chore(contracts): fixed spelling

l1-contracts/contracts/common/L2ContractAddresses.sol
=> chore(L2ContractAddresses): updated ordering of contract address to be sorted asc

l1-contracts/contracts/zksync/facets/Executor.sol, system-contracts/contracts/PubdataChunkPublisher.sol
=> chore(contracts): removed todo comments

system-contracts/SystemContractsHashes.json, system-contracts/bootloader/bootloader.yul
=> fix(bootloader): updated comment to reflect new value

l1-contracts/scripts/deploy.ts
Right now `--only-verifier` still deploys CREATE2 Factory and Multicall3.
In other words, every `zk init` run deploys two copies of the same contracts.
This commit fixes the issue.
=> Fix: early exit in `onlyVerifier` branch

l1-contracts/contracts/bridge/L1ERC20Bridge.sol, l1-contracts/contracts/bridge/L1SharedBridge.sol, l1-contracts/contracts/bridge/interfaces/IL1SharedBridge.sol, l1-contracts/contracts/dev-contracts/test/L1SharedBridgeTest.sol
- Comments for `L1SharedBridge`
- `reinitializer(2)` -> `initializer` (bridge wasn't deployed, so no sense to put version 2)
- Rename of 
- `isWithdrawalFinalizedShared` -> `isWithdrawalFinalized`
- `eraIsEthWithdrawalFinalizedStorageSwitchBatchNumber` -> `eraFirstPostUpgradeBatch`
- `_isLegacyWithdrawal` -> `_isEraLegacyWithdrawal`
- `_msgSender` -> `_prevMsgSender` in `depositLegacyErc20Bridge` (for consistency)
- Remove payable from `l1WethAddress`
- Change type from `address` to `IERC20` in `_depositFunds`
=> Comments and nits Hyperchains

.github/workflows/buld-release.yaml
Fix logic for release naming for gh release
It's processed a little bit wrong for now
=> ci: update logic for determine branch for releases

l1-contracts/scripts/deploy.ts
This PR kind of rolls back https://github.com/matter-labs/era-contracts/commit/ebfac9e385be7b881c6eb8ac297eab0a8bf22741. Letting `Multicall3` and `Create2Factory` be deployed before the `Verifier`.
As it was stated in https://github.com/matter-labs/era-contracts/commit/ebfac9e385be7b881c6eb8ac297eab0a8bf22741,
> Right now `--only-verifier` still deploys CREATE2 Factory and Multicall3. In other words, every `zk init` run deploys two copies of the same contracts. This commit fixes the issue
it is true that `zk init` run deploys two copies of the same contracts (Multicall3 and CREATE2 Factory), it is also true that that commit fixes that. But the introduction of that change breaks the `zk init` run as the `Deploying L1 verifier` step happens before the `Deploying L1 contracts` step (which …
=> fix: Deploy `Multicall3` and `Create2Factory` before deploying `Verifier`

l1-contracts/scripts/deploy-erc20.ts, l1-contracts/scripts/deploy-testkit.ts, l1-contracts/scripts/deploy-testnet-token.ts, l1-contracts/scripts/deploy-withdrawal-helpers.ts, l1-contracts/scripts/migrate-governance.ts, l1-contracts/scripts/read-variable.ts, l1-contracts/scripts/revert-reason.ts, l1-contracts/scripts/verify.ts, l2-contracts/src/deployForceDeployUpgrader.ts, l2-contracts/src/deployTestnetPaymaster.ts, l2-contracts/src/publish-bridge-preimages.ts, l2-contracts/src/upgradeBridgeImpl.ts, l2-contracts/src/verify.ts, system-contracts/scripts/deploy-preimages.ts, system-contracts/scripts/preprocess-bootloader.ts, system-contracts/scripts/utils.ts
Moved the hardhat import to the top of the imports in scripts.
When it was imported later, it caused some of the scripts to fail.
=> fix(scripts): moved hardhat to be the first import

l1-contracts/contracts/zksync/facets/Executor.sol, l1-contracts/contracts/zksync/facets/Getters.sol, l1-contracts/contracts/zksync/interfaces/IGetters.sol, l1-contracts/scripts/deploy.ts
Add a getter for the mode (Validium or Rollup for the moment) for the server to be able to cross-check said mode to avoid inconsistencies in the config.
It is now possible to run the node with an incorrect config that doesn’t match the L1 config.
We should force the node to ask the pre-deployed contracts on L1 in which mode it should run.
=> feat(Validium): Add getter to `Executor.sol` for retrieving the init mode (Validium or Rollup)

l1-contracts/scripts/deploy-erc20.ts
This PR speeds up the ERC20 deployment script used by `zk init` by deploying contracts and minting tokens in parallel.
The previous implementation took 60+ seconds to finish.
=> chore: speed up deploy-erc20 script

l1-contracts/contracts/dev-contracts/test/DiamondCutTestContract.sol, l1-contracts/contracts/dev-contracts/test/MerkleTest.sol, l1-contracts/test/foundry/unit/concrete/Bridges/L1Erc20Bridge/Getters.t.sol, l1-contracts/test/foundry/unit/concrete/state-transition/chain-deps/DiamondProxy/DiamondProxy.t.sol, l1-contracts/test/foundry/unit/concrete/state-transition/chain-deps/facets/Getters/IsFacetFreezable.t.sol, l1-contracts/test/foundry/unit/concrete/state-transition/chain-deps/facets/Getters/_Getters_Shared.t.sol
Removed some `test()` functions from intermediary contracts to display correct coverage, and added new test.
Current coverage stats:
The usage of `test()` function indeed removes the unneeded files (like files from `dev-contracts` folder) from the coverage report, but it results in the coverage not being displayed for the libraries. I removed those functions temporarily, so we could see the real libraries coverage(unfortunately, we will see the dev-contracts as well, but I proposed a small change to foundry https://github.com/foundry-rs/foundry/pull/7301, that would allow us to ignore those files in the future).
=> fix: remove test() functions to display correct coverage

.solhint.json, l2-contracts/contracts/bridge/L2WrappedBaseToken.sol, system-contracts/SystemContractsHashes.json, system-contracts/contracts/libraries/SystemContractHelper.sol
This PR enables the following solhint rules: quotes, imports-on-top, use-forbidden-name, visibility-modifier-order, and reentrancy.
=> solhint: new basic rules

.codespell/.codespellrc, .github/workflows/codespell.yaml, _typos.toml, l1-contracts/contracts/state-transition/IStateTransitionManager.sol, l1-contracts/test/foundry/unit/concrete/Bridgehub/BridgehubMailbox/Deposit.t.sol, l1-contracts/test/foundry/unit/concrete/DiamondCut/Initialization.t.sol, l1-contracts/test/unit_tests/utils.ts, system-contracts/SystemContractsHashes.json, system-contracts/bootloader/bootloader.yul, system-contracts/bootloader/test_infra/src/hook.rs, system-contracts/contracts/test-contracts/KeccakTest.sol, system-contracts/test/Keccak256.spec.ts
This PR adds the typos checker. As you can see having one typos checker is not enough.
=> Add typos checker and fix typos

system-contracts/scripts/compile-yul.ts
Replaces sequential compilation of yul with parallel within one folder.
Shaves off some time from `zk init` for free.
=> chore: Compile yul files in parallel within a single folder

.eslintrc, .solhint.json
We actively use console in our scripts and it is hard for us to migrate to custom errors at this moment. Thus, turning off those warning us they clutter the lint results and prevent us from seeing actionable items
=> Clean up some of the warnings

l2-contracts/src/utils.ts
Current `nonce` obtained and used inside of `publishBytecodeFromL1` is currently out of phase when using a base token different than `ETH`.
Prevent `zk init --base-token-name` from failing.
Note: after this PR merges, the branch `kl-factory` of zksync-era should update it's _contracts_ submodule to the latest commit of `without-1.5.0` containing this changes.
=> Fix: move get nonce to correct location

l1-contracts/contracts/state-transition/IStateTransitionManager.sol, l1-contracts/contracts/state-transition/StateTransitionManager.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Admin.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Mailbox.sol, l1-contracts/contracts/state-transition/chain-deps/facets/ZkSyncStateTransitionBase.sol, l1-contracts/contracts/state-transition/chain-interfaces/IAdmin.sol, l1-contracts/src.ts/deploy.ts, l1-contracts/test/foundry/unit/concrete/state-transition/StateTransitionManager/StateTransitionGovernorZero.t.sol, l1-contracts/test/foundry/unit/concrete/state-transition/StateTransitionManager/_StateTransitionManager_Shared.t.sol
=> KL OZ N09 renaming

l1-contracts/contracts/state-transition/IStateTransitionManager.sol, l1-contracts/contracts/state-transition/StateTransitionManager.sol
=> KL OZ fix L03

l1-contracts/contracts/state-transition/IStateTransitionManager.sol, l1-contracts/contracts/state-transition/StateTransitionManager.sol
=> Kl OZ fix L02

l1-contracts/contracts/state-transition/StateTransitionManager.sol, l1-contracts/contracts/state-transition/ValidatorTimelock.sol
=> Ra N06 add named parameters and improve descriptions

system-contracts/contracts/EvmInterpreter.yul
This PR adds `exp` and `signextend` opcodes to YUL EVM interpreter, as well as tests for them.
=> [EVM-Equivalent-YUL] Add exp and signextend opcodes

system-contracts/contracts/EvmInterpreter.yul
This PR adds `addmod` and `mulmod` opcodes to YUL EVM interpreter, as well as tests for them.
=> [EVM-Equivalent-YUL] Add addmod and mulmod opcodes

system-contracts/contracts/EvmInterpreter.yul
With this change, the function will stop doing N (from pushN) `add`s, but only one, whatever N be.
=> [EVM-Equivalent-YUL] Optimize readBytes function used by pushN opcodes

system-contracts/SystemContractsHashes.json, system-contracts/bootloader/bootloader.yul, system-contracts/contracts/SystemContext.sol
Due to lots of merge conflicts, all the commits except for [this PR](https://github.com/matter-labs/era-contracts/pull/283/files) were cherry-picked
- Removed `MAX_PUBDATA_FOR_TX` to avoid additional limitations for the operator. DDoS protection could be achieved via offchain means.
- Fixed how encoding is checked for `gasLimit` / `gasRefund` since both can be u64
- Decreased `MAX_L2_GAS_PER_PUBDATA` to 50k. The reason behind this is that the latest SDK signs the 50k value by default. We'll increase back to the 2^20
=> Sync dev with the sb-1-5-0-integration branch

system-contracts/contracts/EvmInterpreter.yul
This PR adds `jump` and `jumpi` (also `jumpdest`)
=> [EVM-Equivalent-YUL] Add jump and jumpi opcodes

system-contracts/contracts/EvmInterpreter.yul
This PR adds `lt`, `gt`, `slt`, `sgt`, `eq`, `iszero`, `xor`, `not` and `byte` opcodes
=> [EVM-Equivalent-YUL] Add some logic operators opcodes

system-contracts/contracts/EvmInterpreter.yul
Implement the `dup` opcodes for the EVM interpreter.
=> [EVM-Equivalent-YUL] Add dup opcodes

system-contracts/contracts/EvmInterpreter.yul
Implement the `swap` opcodes for the EVM interpreter.
=> [EVM-Equivalent-YUL] Add swap opcodes

system-contracts/contracts/EvmInterpreter.yul
=> [EVM-Equivalent-Yul] Add memory expansion functions

system-contracts/contracts/EvmInterpreter.yul
This PR adds `mload`, `mstore` and `mstore8` opcodes, including their gas charges.
=> [EVM-Equivalent-Yul] Add mload, mstore and mstore8 opcodes

system-contracts/contracts/EvmInterpreter.yul
Add `block-environment` opcodes.
The following opcodes have to be commented, because  the current version of the compiler doesn't build `blob` functions:
```yul
case 0x49 { // OP_BLOBHASH
evmGasLeft := chargeGas(evmGasLeft, 3)
let blobIndex
blobIndex, sp := popStackItem(sp)
// blobhash() is not found in this version of yul
//sp := pushStackItem(sp, blobhash(blobIndex))
}
case 0x4A { // OP_BLOBBASEFEE
evmGasLeft := chargeGas(evmGasLeft, 2)
// blobbasefee() is not found in this version of yul
//sp := pushStackItem(sp, blobbasefee())
}
```
=> [EVM-Equivalent-YUL] Add block-environment opcodes

.gitignore, system-contracts/package.json, system-contracts/scripts/compile-yul.ts, system-contracts/scripts/preprocess-system-contracts.ts, system-contracts/scripts/utils.ts
[# What ❔
Avoiding compilation, when it is not required
Hardhat caching isn't always working correctly & sometimes we use scripts, so compilation is always triggered. 
](https://github.com/matter-labs/era-contracts/compare/dev-4d6def2...feat/avoid-unnecessary-compilation)
=> extend utils & update compilation process

.github/workflows/l1-contracts-foundry-ci.yaml, l1-contracts-foundry/script-config-template/config-deploy-l1.toml, l1-contracts-foundry/script-config-template/register-hyperchain.toml, l1-contracts-foundry/script/DeployL1.s.sol, l1-contracts-foundry/script/RegisterHyperchain.s.sol, l1-contracts/src.ts/deploy.ts
=> remove redundant configs

system-contracts/contracts/EvmInterpreterFunctions.template.yul, system-contracts/contracts/EvmInterpreterLoop.template.yul
This PR moves the gas charge upper so if the opcode fails and reverts, the gas is charged anyway.
Works with tests on [zksync-era #1837](https://github.com/matter-labs/zksync-era/pull/1837)
=> [EVM-Equivalence-Yul] Move gas charge up on opcodes

.github/workflows/l1-contracts-ci.yaml
=> Add CI coverage

system-contracts/contracts/AccountCodeStorage.sol
`extcodehash` opcode now returns the keccak256 hash of the deployed code instead of the zkevm versioned hash.
This enhance EVM compatibility
=> [EVM-Equivalence-Yul] Fix extcodehash on EVM contracts

system-contracts/contracts/EvmInterpreterLoop.template.yul, system-contracts/contracts/EvmInterpreterPreprocessed.yul
This PR fixes the exp opcode, its gas calculations were incorrect, which made it revert
Tests were added on this [PR](https://github.com/matter-labs/zksync-era/pull/1874)
=> [EVM-Equivalence-YUL]  Fix exp opcode

l1-contracts/scripts/verify.ts, l1-contracts/src.ts/deploy-test-process.ts, l1-contracts/src.ts/deploy.ts, l1-contracts/test/unit_tests/l2-upgrade.test.spec.ts
Uses `CONTRACTS_GENESIS_PROTOCOL_SEMANTIC_VERSION` variable in scripts
We introduce new env variable to keep server config schema backward compatible
=> Use `CONTRACTS_GENESIS_PROTOCOL_SEMANTIC_VERSION` variable

l1-contracts/contracts/common/Config.sol, l1-contracts/contracts/common/libraries/SemVer.sol, l1-contracts/contracts/dev-contracts/test/CustomUpgradeTest.sol, l1-contracts/contracts/state-transition/IStateTransitionManager.sol, l1-contracts/contracts/state-transition/StateTransitionManager.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Getters.sol, l1-contracts/contracts/state-transition/chain-interfaces/IGetters.sol, l1-contracts/contracts/upgrades/BaseZkSyncUpgrade.sol, l1-contracts/contracts/upgrades/BaseZkSyncUpgradeGenesis.sol, l1-contracts/scripts/utils.ts, l1-contracts/scripts/verify.ts, l1-contracts/src.ts/deploy-test-process.ts, l1-contracts/src.ts/deploy.ts, l1-contracts/test/foundry/unit/concrete/state-transition/chain-deps/facets/Admin/ExecuteUpgrade.t.sol, l1-contracts/test/test_config/constant/hardhat.json, l1-contracts/test/unit_tests/l2-upgrade.test.spec.ts, l1-contracts/test/unit_tests/utils.ts
Storing `protocolVersion` as a packed semver value. 
Two potential improvements:
- Store it as `struct` in storage. It gives us more explicit description of what it is. However it causes a much bigger diff code and generally packing will still be needed for the `protocolVersionDeadline` map in STM.
- Store it as 100 * minor + patch. It is more human readable, but not "standard", though we can consider it due to better usability   
Fixes: EVM-637
=> Packed protocol version

l1-contracts/scripts/register-hyperchain.ts, l1-contracts/src.ts/deploy.ts
=> Use governance as hyperchain governor upon init

system-contracts/SystemContractsHashes.json, system-contracts/contracts/L1Messenger.sol
=> chore(l1messenger): charge pubdata for sending l2 to l1 log

system-contracts/SystemContractsHashes.json, system-contracts/bootloader/bootloader.yul
We need to increase these values as we no longer deal solely with eth based chains. Increasing allows operators to accurately charge enough to pay for gas/pubdata/
=> chore(bootloader): increase MAX_ALLOWED_FAIR_PUBDATA_PRICE and MAX_ALLOWED_FAIR_L2_GAS_PRICE for base tokens

system-contracts/contracts/EvmInterpreterFunctions.template.yul, system-contracts/contracts/EvmInterpreterPreprocessed.yul
This PR fixes some bugs on extcodecopy where the destiny for memory was not being handled and if the address didn't have code it reverted instead of returning zeros
Test are on this [PR](https://github.com/matter-labs/zksync-era/pull/2191)
=> [EVM-Equivalence-YUL] Extcodecopy fix

l1-contracts/scripts/register-hyperchain.ts, l1-contracts/src.ts/deploy-process.ts, l1-contracts/src.ts/deploy.ts
- An extra check is added to ensure that the diamond cut hash matches the one stored in the STM.
- Unused CLI params are removed from the `register-hyperchain` command
- setTokenMultiplier call is done via the governance if deployer != admin
- setPubdataPricingMode is not called if deployer != admin
This improves the usability of the scripts which we will (hopefully) use frequently to register new partners on our STM.
=> feat: check diamond cut hash locally

.github/workflows/l1-contracts-ci.yaml
Granting additional permissions for CI generated token
This will fiix problem when external contributors can't get coverage report due to insufficient permissions.
=> chore(ci): Additional permissions for CI token

system-contracts/contracts/EvmInterpreter.template.yul, system-contracts/contracts/EvmInterpreterFunctions.template.yul, system-contracts/contracts/EvmInterpreterLoop.template.yul, system-contracts/contracts/EvmInterpreterPreprocessed.yul
This PR fixes bugs found using era-compiler-tester, most of them related to overflow checks.
A full description of the bugs and their fixes below.
We were not returning gas on reverts, which made a lot of tests fail on a check by the `compiler-tester` after execution where it tried to retrieve gas used from the return data and it was empty. We added gas on reverts so now those errors are no longer there.
Some tests fail because compiling them with the `solc` version used by the project, they internally generate `mcopy` opcodes, which we do not support because we target Shanghai, not Cancun. We added a basic implementation of `mcopy` that makes tests pass, though it's very inefficient since there is no `mcopy` opcode on the zkEVM.
The `mcopy` tests are the following:
- …
=> [EVM-Equivalence-YUL] Fix compiler tester bugs

system-contracts/contracts/EvmInterpreter.template.yul, system-contracts/contracts/EvmInterpreterFunctions.template.yul, system-contracts/contracts/EvmInterpreterLoop.template.yul, system-contracts/contracts/EvmInterpreterPreprocessed.yul
This PR optimizes opcodes by:
1. Moving loop processing in a function and marking it as noinline. This removes a lot of unneeded spills and reloads generated by the compiler.
2. Combining checks for pop and push. LLVM will optimize these checks into a single comparison.
3. Adding always inline to warmAddress address function. This forces LLVM to inline warmAddress function in all places.
=> [EVM-Equivalence-YUL] Optimize opcodes

l1-contracts/contracts/bridge/L1SharedBridge.sol, l1-contracts/contracts/common/L1ContractErrors.sol, l1-contracts/contracts/state-transition/IStateTransitionManager.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Executor.sol
=> N-02 Typographical Errors

gas-bound-caller/contracts/GasBoundCaller.sol, gas-bound-caller/contracts/GasBoundCallerErrors.sol, l1-contracts/contracts/common/L1ContractErrors.sol, l1-contracts/contracts/governance/Governance.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Admin.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Executor.sol, l1-contracts/contracts/upgrades/Upgrade_v1_4_1.sol, l1-contracts/test/foundry/unit/concrete/Executor/Proving.t.sol, l1-contracts/test/foundry/unit/concrete/Executor/Reverting.t.sol, l1-contracts/test/foundry/unit/concrete/Governance/Executing.t.sol, l1-contracts/test/foundry/unit/concrete/Governance/Reentrancy.t.sol, l1-contracts/test/foundry/unit/concrete/state-transition/chain-deps/facets/Admin/ChangeFeeParams.t.sol
=> N-07 Naming Issues

system-contracts/contracts/EvmInterpreterFunctions.template.yul, system-contracts/contracts/EvmInterpreterPreprocessed.yul
Following CodeOracle contract, charge for zkEVM contracts decommits
=> [EVM-Equivalence] Charge for zkEVM Contract Decommits

system-contracts/contracts/EvmInterpreterFunctions.template.yul, system-contracts/contracts/EvmInterpreterLoop.template.yul, system-contracts/contracts/EvmInterpreterPreprocessed.yul
This PR optimizes opcodes by:
1. Adding noinline attribute to genericCreate function. This removes 2 copy instructions from the main loop, and moves them to the opcode handling. These two copies are not needed for each opcode, so instead of doing them regardless, do them where they are needed.
2. Sinking instruction pointer increment to opcode handling. Instruction pointer is incremented in the beginning of each iteration and copy instructions is introduced in majority of opcode handling to preserve the ip value. Instead of doing that, sink ip increment to opcode handling to prevent regalloc to introduce copy instructions.
This PR also fixes issue where uninitialized variable is passed to pushStackItem in genericCreate function.
=> [EVM-Equivalence-YUL] Optimize opcodes further

system-contracts/contracts/ContractDeployer.sol
This PR changes the `createEVM` function on the `ContractDeployer` to add 1 to returned contract nonces (the `incrementDeploymentNonce` function increments it but returns the previous value), as on zkSync deployment nonces start out at zero, while contract nonces on ethereum start at 1 after EIP 161.
=> [EVM Equivalence] Fix evm contract nonces starting at 0 instead of 1

system-contracts/contracts/EvmInterpreterFunctions.template.yul, system-contracts/contracts/EvmInterpreterPreprocessed.yul
This PR fixes the following semantic test:
`solidity/test/libsolidity/semanticTests/various/address_code.sol`
The test was failing on the `EXTODECOPY` opcode implementation, which calls the `CodeOracle` system contract underneath. When the passed `size ` for it was zero, the `staticcall` to the `CodeOracle` would return 0 and the interpreter reverted. This fixes it to check if the `size` specified is zero, and if so, simply does nothing.
=> [EVM-Equivalence-YUL] fix: extcodecopy reverting when size was zero

l1-contracts/contracts/bridgehub/Bridgehub.sol, l1-contracts/contracts/dev-contracts/test/DummySharedBridge.sol, l1-contracts/test/foundry/unit/concrete/Bridgehub/experimental_bridge.t.sol, l1-contracts/test/foundry/unit/concrete/Bridges/L1Erc20Bridge/ClaimFailedDeposit.t.sol, l1-contracts/test/foundry/unit/concrete/Bridges/L1Erc20Bridge/Deposit.t.sol, l1-contracts/test/foundry/unit/concrete/Bridges/L1Erc20Bridge/FinalizeWithdrawal.sol, l1-contracts/test/foundry/unit/concrete/Bridges/L1Erc20Bridge/Reentrancy.t.sol, l1-contracts/test/foundry/unit/concrete/Bridges/L1Erc20Bridge/_L1Erc20Bridge_Shared.t.sol
Increased coverage in bridgehub unit tests, add some cases for two bridges deposit.
Changed order of assert in Bridgehub contract.
Previous tests had low coverage on branches, asserts and types of deposits, theirs permutations.
=> Bridgehub Test Coverage Increase

gas-bound-caller/package.json, l1-contracts/package.json, l1-contracts/src.ts/deploy-test-process.ts, l1-contracts/test/unit_tests/l2-upgrade.test.spec.ts, l1-contracts/test/unit_tests/utils.ts, system-contracts/package.json, system-contracts/scripts/verify-on-explorer.ts, system-contracts/test/BootloaderUtilities.spec.ts, system-contracts/test/Create2Factory.spec.ts, yarn.lock
Changing `zksync-ethers` dependency source to `v5.9.0` version from development branch.
=> fix: zksync-ethers v5 dependency

system-contracts/contracts/EvmInterpreterLoop.template.yul, system-contracts/contracts/EvmInterpreterPreprocessed.yul
Looks like checking offset for overflow happens too late. Also, earlier checking shows better benchmark results in most cases (for some reason).
```
╠═╡ Ergs/gas (-%) ╞═╡ EVMInterpreter M3B3 ╞═╣
║ CALLDATACOPY                       -1.347 ║
║ CODECOPY                           -0.738 ║
║ RETURNDATACOPY                     -1.474 ║
║ MLOAD                               2.840 ║
║ MSTORE8                             5.079 ║
║ SWAP1                               8.496 ║
║ SWAP2                               4.248 ║
║ SWAP3                               4.248 ║
║ SWAP4                               4.248 ║
║ SWAP6                               4.248 ║
║ SWAP7                               4.248 ║
║ SWAP8                               4.248 ║
║ SWAP9                               4.248 ║
║ …
```
=> [EVM-Equivalence-YUL] Check offset overflow earlier in memory opcodes

l1-contracts/contracts/dev-contracts/test/AdminFacetTest.sol, l1-contracts/contracts/dev-contracts/test/DummyHyperchain.sol, l1-contracts/contracts/dev-contracts/test/MailboxFacetTest.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Admin.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Mailbox.sol, l1-contracts/deploy-scripts/DeployL1.s.sol, l1-contracts/src.ts/deploy.ts, l1-contracts/test/foundry/unit/concrete/Bridgehub/experimental_bridge.t.sol, l1-contracts/test/foundry/unit/concrete/DiamondCut/FacetCut.t.sol, l1-contracts/test/foundry/unit/concrete/DiamondCut/UpgradeLogic.t.sol, l1-contracts/test/foundry/unit/concrete/Executor/_Executor_Shared.t.sol, l1-contracts/test/foundry/unit/concrete/state-transition/StateTransitionManager/_StateTransitionManager_Shared.t.sol, l1-contracts/test/foundry/unit/concrete/state-transition/chain-deps/facets/Admin/_Admin_Shared.t.sol, l1-contracts/test/foundry/unit/concrete/state-transition/chain-deps/facets/Mailbox/_Mailbox_Shared.t.sol, l1-contracts/test/unit_tests/governance_test.spec.ts, l1-contracts/test/unit_tests/mailbox_test.spec.ts, l1-contracts/test/unit_tests/proxy_test.spec.ts
Ensure that the gateway-migrated chain does not certain unneeded abilities
=> Limitations for the l2 migrated chain

system-contracts/contracts/EvmInterpreterLoop.template.yul, system-contracts/contracts/EvmInterpreterPreprocessed.yul
Since we don't check whether `JUMPDEST` is a valid **opcode** anyway, we can avoid re-reading the same opcode after jumps.
Benchmark results (without the latest compiler optimizations):
```
╠═╡ Ergs/gas (-%) ╞═╡ EVMInterpreter M3B3 ╞═╣
║ JUMP                               23.558 ║
║ JUMPI                              20.502 ║
║ DUP3                               -4.715 ║
║ CALL                                0.259 ║
║ STATICCALL                          0.259 ║
║ DELEGATECALL                        0.264 ║
╚═══════════════════════════════════════════╝
```
=> [EVM-Equivalence-YUL] Execute JUMPDEST immediately after JUMP/JUMPI

system-contracts/contracts/EvmInterpreterFunctions.template.yul, system-contracts/contracts/EvmInterpreterLoop.template.yul, system-contracts/contracts/EvmInterpreterPreprocessed.yul
This function is meant to check that we can push to the stack after we popped it:
https://github.com/matter-labs/era-contracts/blob/462f011231a70099cec9bec0dc4c0ae709b9e039/system-contracts/contracts/EvmInterpreterFunctions.template.yul#L167-L174
However, it is guaranteed since we will put no more elements into the stack than we will pop
=> [EVM-Equivalence-YUL] Remove pop push check

system-contracts/contracts/EvmInterpreterFunctions.template.yul, system-contracts/contracts/EvmInterpreterPreprocessed.yul
=> [EVM Equivalence in Yul] fix: Don't charge the regular cost of the call when calling precompiles

l1-contracts/contracts/bridgehub/Bridgehub.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Mailbox.sol, l1-contracts/deploy-scripts/Gateway.s.sol, l1-contracts/scripts/sync-layer.ts, l1-contracts/src.ts/deploy.ts, l1-contracts/test/foundry/unit/concrete/state-transition/chain-deps/facets/Mailbox/ProvingL2LogsInclusion.t.sol, l1-contracts/test/unit_tests/l1_shared_bridge_test.spec.ts, l1-contracts/test/unit_tests/legacy_era_test.spec.ts
- Correct checks for batch being finalized
- L2->L1 messaging that is compatible with migrating back and forth from gateway
=> Gateway L2->L1 messaging fixes

l1-contracts/contracts/bridge/L1SharedBridge.sol, l1-contracts/contracts/bridge/interfaces/IL1SharedBridge.sol, l1-contracts/test/foundry/unit/concrete/Bridges/L1SharedBridge/L1SharedBridgeAdmin.t.sol, l1-contracts/test/foundry/unit/concrete/Bridges/L1SharedBridge/L1SharedBridgeFails.t.sol, l1-contracts/test/foundry/unit/concrete/Bridges/L1SharedBridge/_L1SharedBridge_Shared.t.sol
=> Add admin role to shared bridge

system-contracts/contracts/EvmInterpreterFunctions.template.yul, system-contracts/contracts/EvmInterpreterLoop.template.yul, system-contracts/contracts/EvmInterpreterPreprocessed.yul
=> [EVM-Equivalence-YUL] Interpeter optimizations

l1-contracts/contracts/common/Config.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Mailbox.sol, l1-contracts/test/foundry/unit/concrete/state-transition/chain-deps/facets/Mailbox/ProvingL2LogsInclusion.t.sol
Support old format for L2->L1 logs
=> Support old L2->L1 log proving format

.eslintrc, l1-contracts/foundry.toml, l1-contracts/lib/openzeppelin-contracts-upgradeable-v4, l1-contracts/lib/openzeppelin-contracts-v4, system-contracts/SystemContractsHashes.json, system-contracts/bootloader/bootloader.yul
=> chore(config): Fix server build with symlinks

system-contracts/contracts/EvmInterpreterFunctions.template.yul, system-contracts/contracts/EvmInterpreterLoop.template.yul, system-contracts/contracts/EvmInterpreterPreprocessed.yul
Instead of calling an oracle and decommiting the code, the length can be obtained from the hash. Using the same logic as in `CodeOracle.yul`. In addition, we can use this logic for both types of contracts, which allows us to remove the extra call to check the contract type.
Result observed:
```
╠═╡ Ergs/gas (-%) ╞═╡ EVMInterpreter M3B3 ╞═╣
║ EXTCODESIZE                        46.828 ║
║ CALL                                0.085 ║
║ STATICCALL                          0.086 ║
║ DELEGATECALL                        0.086 ║
║ CREATE                              0.042 ║
║ CREATE2                             0.044 ║
╚═══════════════════════════════════════════╝
```
=> [EVM-Equivalence-YUL] Simplify EXTCODESIZE

l1-contracts/package.json
Yarn clean should also remove 'ZKSync' artifacts.
Right now we compile the l1-contracts both for 'l1' (as EVM) and for gateway (as ZKSync artifacts)
=> fix: Fixed yarn clean - to remove zksync artifacts too

system-contracts/contracts/ContractDeployer.sol
Using mapping requires hashing the key, which is quite expensive.
Benchmark results:
```
╠═╡ Ergs/gas (-%) ╞═╡ EVMInterpreter M3B3 ╞═╣
║ EXTCODEHASH                         3.626 ║
║ CREATE                              0.298 ║
║ CREATE2                             0.313 ║
╚═══════════════════════════════════════════╝
```
=> [EVM-Equivalence-YUL] Implement evmCodeHash without mapping

l1-contracts/contracts/bridge/L1SharedBridge.sol
Bytes encoding of strings replaced with "abi.encode".
These bytes arrays are not valid abi encoding and thus cannot be decoded in the decodeString function of the L2StandardERC20 contract.
=> Small PR to Fix "Ethers" and "ETH" encoding

l1-contracts/contracts/bridgehub/Bridgehub.sol, l1-contracts/contracts/bridgehub/IBridgehub.sol, l1-contracts/contracts/common/L1ContractErrors.sol, l1-contracts/deploy-scripts/Utils.sol, l1-contracts/test/foundry/l1/integration/GatewayTests.t.sol, l1-contracts/test/foundry/l1/integration/_SharedZKChainDeployer.t.sol, l1-contracts/test/foundry/l1/unit/concrete/Bridgehub/experimental_bridge.t.sol
=> chore: merge stable

l1-contracts/deploy-scripts/DeployL2Contracts.sol, l1-contracts/deploy-scripts/dev/SetupLegacyBridge.s.sol, l1-contracts/deploy-scripts/dev/SetupLegacybridge.sol
=> Deploy legacy bridge inside foundry

l1-contracts/scripts/sync-layer.ts, l1-contracts/src.ts/deploy.ts
Script to compute a chain's diamond proxy address on gateway via CREATE2.
We need to know it before the chain is migrated, to put in configs and such.
=> feat: compute migrated chain's diamond proxy address

l1-contracts/contracts/state-transition/data-availability/ValidiumL1DAValidator.sol, l1-contracts/deploy-scripts/DeployL1.s.sol, l1-contracts/deploy-scripts/DeployL2Contracts.sol, l1-contracts/deploy-scripts/GatewayCTMFromL1.s.sol, l1-contracts/deploy-scripts/L2ContractsBytecodesLib.sol, l1-contracts/deploy-scripts/Utils.sol, l1-contracts/src.ts/deploy.ts, l2-contracts/contracts/verifier/TestnetVerifier.sol
Ensure that Validium and ERC20 chains are supported on top of gateway
=> Improve variety of chains sync layer stable

l1-contracts/contracts/bridgehub/IBridgehub.sol, l1-contracts/contracts/common/L1ContractErrors.sol, l1-contracts/contracts/governance/IPermanentRestriction.sol, l1-contracts/contracts/governance/L2AdminFactory.sol, l1-contracts/contracts/governance/PermanentRestriction.sol, l1-contracts/package.json, l1-contracts/test/foundry/l1/integration/deploy-scripts/script-config/config-deploy-zk-chain-10.toml, l1-contracts/test/foundry/l1/integration/deploy-scripts/script-config/config-deploy-zk-chain-11.toml, l1-contracts/test/foundry/l1/integration/deploy-scripts/script-config/config-deploy-zk-chain-era.toml, l1-contracts/test/foundry/l1/unit/concrete/Governance/PermanentRestriction.t.sol, l1-contracts/test/foundry/l2/unit/L2AdminFactory/L2AdminFactory.t.sol
=> Better governance protection (audit)

l1-contracts/deploy-scripts/EIP712Utils.sol, l1-contracts/deploy-scripts/Utils.sol, l1-contracts/deploy-scripts/interfaces/IEmergencyUpgrageBoard.sol, l1-contracts/deploy-scripts/interfaces/IMultisig.sol, l1-contracts/deploy-scripts/interfaces/IProtocolUpgradeHandler.sol, l1-contracts/deploy-scripts/interfaces/ISafe.sol
=> Add utils for DecentralizeGovernance transaction

system-contracts/contracts/EvmInterpreter.yul, system-contracts/evm-interpreter/EvmInterpreterFunctions.template.yul, system-contracts/evm-interpreter/EvmInterpreterLoop.template.yul
This PR adds all unused opcodes.
Since opcodes are 8-bit long and if we implement all cases in the switch of that range (0-255), LLVM will optimize out default case (as it is shown [here](https://godbolt.org/z/sc5rdv361) where for default case will generate unreachable BB), thus will remove checks before jump table instruction. As a result, this will remove 1 instruction that is executed in a loop header for each opcode.
Before this patch, we had following assembly generated in a loop header:
```
sub.s	31, r14, r1
ldmi.h	r1, r2, r14
and	255, r2, r2
sub.s!	255, r2, r0        <- This check is not needed
jump.ne	code[@JTI3_0+r2]
jump	@.BB3_1053         <- This branch is not needed
```
After this patch:
```
sub.s	31, r14, r1
ldmi.h	r1, r2, r14
and	255, r2, r2
jump	code[@JTI3_0+r2]
```
=> feat(EVM-emulator): add all unused opcodes

l2-contracts/contracts/ConsensusRegistry.sol
Restricted both changeValidatorKey and changeAttesterKey functions to be only callable by the contract's owner.
Fixes L-01
=> fix: Node Owner Can Set Invalid Key and Signature Values

l2-contracts/contracts/ConsensusRegistry.sol
Added a constructor that calls `_disableInitializers()`.
=> fix: ConsensusRegistry Contract's Constructor Does Not Call _disableinitializers()

l2-contracts/contracts/ConsensusRegistry.sol, l2-contracts/contracts/interfaces/IConsensusRegistry.sol
Limited the `getAttesterCommittee`, `getValidatorCommittee`, and `numNodes` functions to external visibility. This fixes N-03.
Also added `numNodes` to the interface, which seemed to be an oversight.
=> fix: Function Visibility Overly Permissive

l2-contracts/contracts/ConsensusRegistry.sol, l2-contracts/contracts/interfaces/IConsensusRegistry.sol
=> docs: Misleading Documentation

l2-contracts/contracts/ConsensusRegistry.sol
Renamed several functions:
- `_isNodeOwnerExists`  to `_doesNodeOwnerExist`
- `_ensureAttesterSnapshot` to `_snapshotAttesterIfOutdated`
- `_ensureValidatorSnapshot` to `_snapshotValidatorIfOutdated`
=> style: Naming Suggestions

l2-contracts/contracts/ConsensusRegistry.sol, l2-contracts/contracts/interfaces/IConsensusRegistry.sol
Replaced `InvalidInputNodeOwnerAddress` error with the already existing `ZeroAddress` error. Also deleted unused error `NodeOwnerNotFound`.
Fixes N-01.
=> fix: Misleading Errors

l2-contracts/contracts/ConsensusRegistry.sol, l2-contracts/contracts/interfaces/IConsensusRegistry.sol
- Made activate/deactivate functions specific to attester and validator.
- Limited activate functions to be called by contract owner.
=> fix: Redundant Logic

system-contracts/contracts/EvmEmulator.yul.llvm.options
Tweak LLVM options for lazy stack implementation of EvmEmulator.
To improve performance numbers (which can be seen [here](https://github.com/matter-labs/era-compiler-tester/pull/98)).
=> feat(EVM-emulator): tweak LLVM options for lazy stack implementation

system-contracts/SystemContractsHashes.json, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulator.template.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> Feat(EVM): Use different memory layouts for constructor and deployed contract

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulator.template.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
It should not revert, but return zeroes for out-of-bounds regions of bytecode
=> fix(EVM): Fix bytecode read operations

system-contracts/SystemContractsHashes.json, system-contracts/contracts/EvmEmulator.yul, system-contracts/contracts/EvmGasManager.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Warm origin and sender accounts

system-contracts/SystemContractsHashes.json, system-contracts/contracts/ContractDeployer.sol, system-contracts/contracts/EvmEmulator.yul, system-contracts/contracts/interfaces/IContractDeployer.sol, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> feat(EVM): Simplify returngas from constructor

system-contracts/contracts/ContractDeployer.sol
=> chore(EVM): Cleanup in contract deployer

system-contracts/SystemContractsHashes.json, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Fix data copy corner cases

l1-contracts/deploy-scripts/DeployL2Contracts.sol, l1-contracts/deploy-scripts/L2ContractsBytecodesLib.sol, l2-contracts/contracts/dev-contracts/ITimestampAsserter.sol, l2-contracts/contracts/dev-contracts/TimestampAsserter.sol
Adds TimestampAsserter to sync-layer-stable
Required to port zksync-era:main changes to sync-layer-stable
=> add TimestampAsserter to sync-layer-stable

.solhint.json, system-contracts/SystemContractsHashes.json, system-contracts/contracts/L2BaseToken.sol, system-contracts/contracts/interfaces/IBaseToken.sol, system-contracts/test/L2BaseToken.spec.ts
Remove Name, Symbol and Decimal from L2BaseToken.sol
Multiple issues with those methods :
1- For hyperchains that does not use ETH as base token, the values returned by those methods are wrong so it should not be hardcoded. I couldnt find a good way to make them variable without heavy changes on the initialisation process
2- L2BaseToken IS not an ERC20 as it does not implement IERC20 interface (no approval or allowance) but it looks like it which confuse some explorers
One example is on https://era.zksync.network/
The value of ETH is counted twices as it is also recorded as an ERC20
https://era.zksync.network/address/0xd0c511bdbf219e3d5793e47b9ad559c9f69b3404
We should remove all confusion and make "symbol" and "name" agnostics as it is done on Ethereum
=> feat(system-contracts): remove unecessary methods from L2BaseToken.sol

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Fix CALL in static context

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Zero out frame gas left for underpaid precompiles 

l1-contracts/deploy-scripts/DeployL1.s.sol, l1-contracts/deploy-scripts/DeployL2Contracts.sol, l1-contracts/deploy-scripts/RegisterHyperchain.s.sol, system-contracts/scripts/calculate-hashes.ts, system-contracts/scripts/preprocess-bootloader.ts
=> Fix deploy scripts after merging dev

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
We should:
- Not revert caller frame on DELEGATECALL to EraVM contracts
- Get the same result from precompiles as using CALL
- Allow delegatecalls to empty contracts
=> fix(EVM): Make DELEGATECALL behavior closer to EVM

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
We can have contracts without any code, but with some code hash associated
=> fix(EVM): Make fetchDeployedCode more robust

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Increase max allowed memory (2)

yarn.lock
=> chore(EVM): Merge V25 release branch

l1-contracts/contracts/common/L1ContractErrors.sol, l1-contracts/contracts/dev-contracts/DummyRestriction.sol, l1-contracts/contracts/governance/AccessControlRestriction.sol, l1-contracts/contracts/governance/ChainAdmin.sol, l1-contracts/contracts/governance/L2AdminFactory.sol, l1-contracts/contracts/governance/PermanentRestriction.sol, l1-contracts/contracts/governance/restriction/IRestriction.sol, l1-contracts/contracts/governance/restriction/Restriction.sol, l1-contracts/contracts/governance/restriction/RestrictionValidator.sol, l1-contracts/deploy-scripts/DeployL1.s.sol, l1-contracts/test/foundry/l1/integration/GatewayTests.t.sol, l1-contracts/test/foundry/l1/unit/concrete/Governance/AccessControlRestriction.t.sol, l1-contracts/test/foundry/l1/unit/concrete/Governance/ChainAdmin.t.sol, l1-contracts/test/foundry/l1/unit/concrete/Governance/PermanentRestriction.t.sol, l1-contracts/test/foundry/l1/unit/concrete/state-transition/libraries/TransactionValidator/ValidateL1L2Tx.t.sol, l1-contracts/test/foundry/l2/unit/L2AdminFactory/L2AdminFactory.t.sol
=> feat: OZ ZKChain: Governance Audit Fixes Combines

system-contracts/contracts/ContractDeployer.sol, system-contracts/contracts/EvmEmulator.yul, system-contracts/contracts/KnownCodesStorage.sol, system-contracts/contracts/SystemContractErrors.sol, system-contracts/contracts/interfaces/IKnownCodesStorage.sol, system-contracts/contracts/libraries/Utils.sol, system-contracts/contracts/precompiles/CodeOracle.yul, system-contracts/evm-emulator/EvmEmulator.template.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul, system-contracts/test/KnownCodesStorage.spec.ts
The previously used versioned bytecode hash encoding is inefficient. For EVM contracts, we can store the length of the **original unpadded** EVM bytecode directly in the hash to simplify the logic of `EXTCODESIZE`.
=> fix(EVM): Store unpadded EVM bytecode length in versioned bytecode hash

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
It is cleaner and more efficient to truncate by actual bytecode length.
=> fix(EVM): Simplify and optimize out-of-bounds truncation in `CODECOPY`

system-contracts/contracts/ContractDeployer.sol, system-contracts/contracts/EvmEmulator.yul, system-contracts/contracts/KnownCodesStorage.sol, system-contracts/contracts/SystemContractErrors.sol, system-contracts/contracts/interfaces/IKnownCodesStorage.sol, system-contracts/contracts/libraries/Utils.sol, system-contracts/contracts/precompiles/CodeOracle.yul, system-contracts/evm-emulator/EvmEmulator.template.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul, system-contracts/test/KnownCodesStorage.spec.ts
The previously used versioned bytecode hash encoding is inefficient. For EVM contracts, we can store the length of the **original unpadded** EVM bytecode directly in the hash to simplify the logic of `EXTCODESIZE`.
=> fix(EVM): Store unpadded EVM bytecode length in versioned bytecode hash (updated)

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulator.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul, system-contracts/evm-emulator/calldata-opcodes/ConstructorScope.template.yul, system-contracts/evm-emulator/calldata-opcodes/RuntimeScope.template.yul
Calldata should be empty in constructor.
=> fix(EVM): Handle calldata-related opcodes in constructor

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Use static call for isSlotWarm (L-07)

system-contracts/contracts/EvmEmulator.yul, system-contracts/contracts/KnownCodesStorage.sol, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul, system-contracts/evm-emulator/calldata-opcodes/RuntimeScope.template.yul
=> fix(EVM): Fix namings (N-02)

system-contracts/contracts/ContractDeployer.sol
=> fix(EVM): Simplify set constructing bytecode hash (N-07)

system-contracts/contracts/EvmEmulator.yul, system-contracts/contracts/libraries/Utils.sol, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Remove magic numbers (N-09)

system-contracts/contracts/EvmEmulator.yul, system-contracts/contracts/SystemContext.sol, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Use constant PREVRANDAO value (N-11)

system-contracts/contracts/EvmEmulator.yul, system-contracts/contracts/EvmGasManager.yul, system-contracts/evm-emulator/EvmEmulator.template.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul, system-contracts/evm-emulator/EvmEmulatorLoopUnusedOpcodes.template.yul
The INVALID opcode and other panics must mimic the behavior of `revert(0,0)` (so the EraVM environment will not receive unexpected returndata), but the emulator produces `revert(0,32)` instead, exhibiting an inconsistency.
This PR modifies panics, so now nothing will be returned if caller is not EVM.
Also made small changes to offset added overhead.
=> fix(EVM): Fix cross vm panic returndata logic (L-03)

system-contracts/contracts/ContractDeployer.sol
=> fix(EVM): Simplify ContractDeployer storage layout

system-contracts/contracts/ContractDeployer.sol, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Small misc fixes

system-contracts/contracts/ContractDeployer.sol, system-contracts/contracts/EvmEmulator.yul, system-contracts/contracts/precompiles/CodeOracle.yul, system-contracts/evm-emulator/EvmEmulator.template.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul, system-contracts/evm-emulator/calldata-opcodes/RuntimeScope.template.yul
=> fix(EVM): Additional fixes after review

.github/workflows/l1-contracts-ci.yaml, .github/workflows/system-contracts-ci.yaml, system-contracts/scripts/calculate-hashes.ts
=> chore: Merge main in dev

docs/upgrade_history/gateway_upgrade/upgrade_process (no gateway chain).md
=> Describe upgrade process without gateway

system-contracts/contracts/precompiles/EcAdd.yul, system-contracts/contracts/precompiles/EcMul.yul, system-contracts/contracts/precompiles/EcPairing.yul, system-contracts/contracts/precompiles/Modexp.yul
* ECPairing to handle the internal error correctly
* Proper reverts (instead of returns) for other precompiles too
=> fix: correct reverts & internal errors from ecpairing

system-contracts/contracts/precompiles/EcMul.yul, system-contracts/contracts/precompiles/EcPairing.yul, system-contracts/contracts/precompiles/Modexp.yul
- Modexp: Fixed an issue where numbers shorter than 32 bytes were not handled correctly.
- EcPairing: Added overflow protection for gasCost.
=> Fix precompiles wrappers

system-contracts/contracts/EvmEmulator.yul, system-contracts/contracts/EvmGasManager.yul, system-contracts/evm-emulator/EvmEmulator.template.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> feat(EVM): Store bytecode in the active pointer

.github/workflows/invariant-tests.yaml, .github/workflows/l1-contracts-ci.yaml
Introducing the invariant tests workflow.
We want to run invariant tests on schedule. This is possible only if the workflow is on the default branch which is currently `main`. On the other hand, it doesn't make sense to merge  https://github.com/matter-labs/era-contracts/pull/1237. to `main` yet because the `main` doesn't have the target code to test (i.e. the `main` is far behind `dev`).
So in order for https://github.com/matter-labs/era-contracts/pull/1237 to work we need to merge this PR. Later `dev` will be merged to `main` adding the missing code.
=> Add invariant tests workflow and fix coverage job

l1-contracts/foundry.toml
This PR reduces the the `depth` parameter.
GitHub enforces the [6 hour job run limit](https://docs.github.com/en/actions/administering-github-actions/usage-limits-billing-and-administration) so both scheduled and manual workflow runs have failed for the L1 context. Looks like [runs=10 and depth=100000](https://github.com/matter-labs/era-contracts/blob/4518328108a348c5e656b06018a37ef64018f497/l1-contracts/foundry.toml#L76-L77) is too much for the CI. Reducing the depth to 10000.
Failed workflows:
- https://github.com/matter-labs/era-contracts/actions/runs/13534543437
- https://github.com/matter-labs/era-contracts/actions/runs/13524069214
=> Reduce the `depth` parameter for invariant tests in the L1 context

system-contracts/contracts/precompiles/Modexp.yul
=> N-03: Modexp Lacks an SPDX License Identifier

system-contracts/contracts/precompiles/Modexp.yul
=> L-01: Hardcoded Modular Length Value in Return Statement

system-contracts/contracts/precompiles/EcPairing.yul
=> M-01: Return Length of ‘EcPairing’ Does Not Match the Specifications

.github/workflows/l1-contracts-ci.yaml, AllContractsHashes.json, l1-contracts/contracts/state-transition/verifiers/L1VerifierFflonk.sol, l1-contracts/contracts/state-transition/verifiers/L2VerifierFflonk.sol, l1-contracts/package.json, tools/data/fflonk_verifier_contract_template.txt
Un-stacked FFLONK (removed stack-too-deep issue when running coverage).
Coverage CI is temporarily removed since v27.
=> Restore coverage CI by unstacking fflonk verifier

AllContractsHashes.json, system-contracts/bootloader/bootloader.yul, system-contracts/scripts/preprocess-bootloader.ts
Fix for an issue that disallowed `createEVM`/`create2EVM` calls to `ContractDeployer`.
Currently, calls to `createEVM`/`create2EVM` will always fail, because the system call flag isn't applied on a call to those functions.
This PR is intended to gain the ability to call them.
=> fix: allow createEVM/create2EVM system calls

AllContractsHashes.json, l1-contracts/contracts/dev-contracts/DummyChainTypeManager.sol, l1-contracts/contracts/governance/ChainAdmin.sol, l1-contracts/test/foundry/l1/unit/concrete/Governance/ChainAdmin.t.sol
`ChainTypeManager` address was added as a parameter to `setUpgradeTimestamp` function in `ChainAdmin` contract.
It's used to verify whether protocol version parameter in `setUpgradeTimestamp` is indeed active.
It's being included as a quality-of-life improvement for chain admins, that verifies whether protocol version they specified is valid, and reverts with `InvalidProtocolVersion` error if not.
=> feat: add verification of of protocolVersion in setUpgradeTimestamp

AllContractsHashes.json, l1-contracts/contracts/state-transition/ChainTypeManager.sol, l1-contracts/contracts/state-transition/IChainTypeManager.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Admin.sol, l1-contracts/contracts/state-transition/chain-interfaces/IAdmin.sol
- Add preimages of `diamondCut` and `forceDeploymentsData` to `NewChainCreationParams` that's being emitted whenever parameters with which a new chain is created are updated.
- Add getter for RollupDAManager in Admin facet.
In order to ensure that we do not need environment config files, we'll need to display the full preimage for chain creation parameters in events.
=> Add full preimages in chain creation parameters event, add getter for RollupDAManager

system-contracts/contracts/PubdataChunkPublisher.sol, system-contracts/contracts/interfaces/IPubdataChunkPublisher.sol, system-contracts/test/PubdataChunkPublisher.spec.ts
We can pass most of chunks to keccak by pointer, without copying them to memory.
=> feat: Use EfficientCall for keccak in pubdata chunk publisher

l1-contracts/package.json, l1-contracts/test/foundry/l1/integration/AssetRouterTest.t.sol, l1-contracts/test/foundry/l1/integration/DeploymentTest.t.sol, l1-contracts/test/foundry/l1/integration/L1GatewayTests.t.sol, l1-contracts/test/foundry/l1/integration/utils/_ConfigSemaphore.sol
Several tests use same local config files in `prepare()` step. Due to parallel test execution we have race condition here and this leads to very flaky tests. This PR adds some kind of semaphore that seems to be working.
Note: this solution is far from ideal and should be replaced with proper scripts/tests refactoring in the future.
=> fix: Implement semaphore for configs

.github/workflows/l1-contracts-ci.yaml
Ignore ChainRegistrar and GatewayTransactionFilterer contracts in coverage since they are unused. Once they will be used, tests for them will be competed (currently located in `l1-contracts/test/foundry/unit/concrete/...` and the contracts will be included in coverage.
=> test: ignore unused files in coverage

AllContractsHashes.json, recompute_hashes.sh
The `recompute_hashes.sh` fails with the following error:
```
...
Cloning into '/Users/nikitastupin/github.com/matter-labs/era-contracts/lib/openzeppelin-contracts-v4/lib/forge-std/lib/ds-test'...
Submodule path 'lib/openzeppelin-contracts-v4/lib/forge-std/lib/ds-test': checked out '6da7dd8f7395f83e1fb6fa88a64ba9a030f85d4f'
./recompute_hashes.sh: line 33: pushd: da-contracts: No such file or directory
```
I've refactored the script and now it works.
=> Fix and refactor `recompute_hashes.sh`

.github/pull_request_template.md, .github/workflows/build-release.yaml, .github/workflows/codespell.yaml, .github/workflows/invariant-tests.yaml, .github/workflows/l1-contracts-ci.yaml, .github/workflows/l2-contracts-ci.yaml, .github/workflows/nodejs-license.yaml, .github/workflows/secrets_scanner.yaml, .github/workflows/slither.yaml, .github/workflows/system-contracts-ci.yaml
- Harden the security of our workflows by restricting the workflow permissions according to the principle of least privilege. Reported by the [CodeQL scanning](https://github.com/matter-labs/era-contracts/security/code-scanning).
- Fix the pull request template formatting.
To minimize the impact of compromised workflows/actions/dependencies.
=> Restrict workflow permissions

AllContractsHashes.json, system-contracts/contracts/SystemContext.sol, system-contracts/test/SystemContext.spec.ts
Given that l2 blocks can now have same timestamps, it doesn't make any sense to require the timestamp of the batch to be greater than the timestamp of the last L2 block. Change to only require `new_batch.timestamp >= prev_block.timestamp` 
See above
=> feat: weaken timestamp restriction in `_ensureBatchConsistentWithL2Block`

l1-contracts/contracts/state-transition/verifiers/DualVerifier.sol
* A mock verifier that only compares public inputs, and doesn't do SNARK verification
* this way we can test almost all the logic, but without the expensive SNARK creation (useful for local testing)
* currently has assert that it works only against 31337 network (local anvil)
=> feat: Mock verifier

l1-contracts/scripts/errors-lint.ts
Uploads error signatures to https://www.4byte.directory/ when running `yarn errors-lint --fix` inside `l1-contracts`. Note that the presence of signatures in this database is **not** checked as part of CI as it can be quite slow (~3 minutes) to iterate through all errors. This directory is used by our own [anvil-zksync](https://github.com/matter-labs/anvil-zksync) as well as other third parties when decoding errors, hopefully making debugging tasks easier for all.
=> chore: upload error signatures when `--fix`ing

da-contracts/contracts/da-layers/eigenda/EigenDAL1DAValidator.sol, l1-contracts/deploy-scripts/ContractsBytecodesLib.sol, l1-contracts/deploy-scripts/DeployL1.s.sol, l1-contracts/deploy-scripts/DeployL2Contracts.sol, l1-contracts/deploy-scripts/DeployUtils.s.sol, l2-contracts/contracts/data-availability/EigenDAL2DAValidator.sol
This PR adds contracts for EigenDA M1
Replaces old [PR](https://github.com/matter-labs/era-contracts/pull/1405) due to change in branch destination
It receives the inclusion data, with the following format
```rust
struct EigenDAInclusionData {
bytes seal;
bytes32 imageId;
bytes32 journalDigest;
bytes32 eigenDAHash;
}
```
It uses a risc zero verifier to verify that the proof generated in the sidecar is correct.
It also compares the hash calculated in the sidecar against the one passed through `L2->L1 Logs`
It calculates the `fullPubdataHash` that will be sent through `L2->L1 Logs`
Related to: https://github.com/matter-labs/zksync-era/pull/4232
=> feat(eigenda): EigenDA M1

system-contracts/contracts/DefaultAccountNoSecurity.sol
Ports `createEVM` logic from `DefaultAccount::executeTransaction` to `DefaultAccountNoSecurity::executeTransaction`.
EVM interpreter create would fail if using `DefaultAccountNoSecurity` due to the missing dispatch.
=> fix createEVM call for DefaultAccountNoSecurity

.github/workflows/build-release.yaml, .gitignore, _typos.toml, docs/evm_emulation/technical_overview.md
* compile contracts and add them to releases
* This will happen either manually, or on tag creation.
* Allows zksync-era CI to run a little bit faster (as it doesn't have to recompile everything - and this is its current bevaviour).
=> fix: Create contract artifacts and add them to releases
