matter-labs/era-contracts

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/SECURITY.md, .github/pull_request_template.md, CONTRIBUTING.md
This PR  adds 
- CONTRIBUTION.md
- SECURITY.md
- Issues templates
- PR templates
=> Add FOS Templates

ethereum/contracts/dev-contracts/test/VerifierRecursiveTest.sol, ethereum/contracts/dev-contracts/test/VerifierTest.sol, ethereum/contracts/zksync/Verifier.sol, ethereum/test/unit_tests/verifier.spec.ts
There is a flag added to VK that shows if we need to check recursive part
For wrapper simplicity and optimizations
=> Non recursive L1 verifier mode

.github/SECURITY.md, CONTRIBUTING.md, zksync/package.json
Resolving conflicts of the PR #32
=> Syncing dev with main

ethereum/test/unit_tests/transaction_validator_test.spec.ts
Fix unit tests for contracts
Fix unit tests
- [+] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [+] Tests for the changes have been added / updated.
- [+] Documentation comments have been added / updated.
- [+] Code has been formatted via `zk fmt` and `zk lint`.
=> Fix unit tests for boojum integration

ethereum/contracts/zksync/facets/Executor.sol
- Fix warning of having unused variable in internal function
- Improve code quality
=> Remove redundant variable in smart contracts

ethereum/contracts/zksync/facets/Admin.sol
Update event emitted by `setPendingAdmin` 
We were emitting the wrong event, this updates the function to emit the correct event.
=> Update event emitted by setPendingAdmin

ethereum/contracts/zksync/facets/Admin.sol, ethereum/contracts/zksync/facets/Executor.sol, ethereum/contracts/zksync/interfaces/ILegacyGetters.sol
Removed unused imports.
For better readability and to saves some gas.
=> chore: remove unused imports

ethereum/scripts/initialize-l2-weth-token.ts, ethereum/src.ts/deploy.ts
After the rollback of the OZ version, zk init stopped working. This PR fixes it
=> Fix scripts

zksync/src/upgradeL2BridgeImpl.ts
=> Fix bridge upgrade script

ethereum/scripts/initialize-l2-weth-token.ts, ethereum/src.ts/deploy.ts
Scripts were fixed
To make it work
=> Small fixes in the scripts

ethereum/contracts/zksync/Verifier.sol, ethereum/contracts/zksync/facets/Admin.sol, ethereum/contracts/zksync/facets/Executor.sol, ethereum/contracts/zksync/facets/Getters.sol, ethereum/contracts/zksync/facets/Mailbox.sol, ethereum/contracts/zksync/interfaces/IAdmin.sol, ethereum/contracts/zksync/interfaces/IBase.sol, ethereum/contracts/zksync/interfaces/IExecutor.sol, ethereum/contracts/zksync/interfaces/IGetters.sol, ethereum/contracts/zksync/interfaces/ILegacyGetters.sol, ethereum/contracts/zksync/interfaces/IMailbox.sol, ethereum/contracts/zksync/interfaces/IVerifier.sol, tools/data/verifier_contract_template.txt
Moved the documentation to the interfaces to ensure that both interfaces and the implementation have docstrings
=> Add missing documentation

ethereum/contracts/zksync/facets/Executor.sol
=> Remove unused function

ethereum/contracts/zksync/facets/Base.sol, ethereum/test/unit_tests/governance_test.spec.ts
Using error codes for consistency
=> Use consistent error codes

ethereum/contracts/zksync/facets/Executor.sol, ethereum/contracts/zksync/facets/Mailbox.sol
=> Remove unneeded override

.github/workflows/buld-release.yaml
=> Fix lint in the yaml file

.github/workflows/buld-release.yaml, .github/workflows/l1-contracts-ci.yaml, .github/workflows/l2-contracts-ci.yaml, .github/workflows/system-contracts-ci.yaml
=> Sync dev with main

l1-contracts/contracts/upgrades/Upgrade_v1_4_1.sol
Use correct variable from the system config
=> Correctly generate constant

ethereum/contracts/bridge/interfaces/IL1Bridge.sol, ethereum/contracts/bridge/interfaces/IL1BridgeLegacy.sol, ethereum/contracts/governance/IGovernance.sol, ethereum/contracts/zksync/libraries/LibMap.sol, zksync/contracts/bridge/interfaces/IL1Bridge.sol
=> Add security contact

ethereum/contracts/common/libraries/L2ContractHelper.sol, ethereum/contracts/zksync/libraries/Diamond.sol, zksync/contracts/L2ContractHelper.sol, zksync/contracts/bridge/L2StandardERC20.sol
To improve clarity, we use more clear visibility for variables and constants
=> Use more clear visibility for variables and constants

zksync/contracts/bridge/L2Weth.sol
Mention some of the L2Weth-specific methods
=> Better docs for L2Weth

ethereum/test/foundry/unit/concrete/Admin/Authorization.t.sol, ethereum/test/foundry/unit/concrete/Admin/_Admin_Shared.t.sol
Add additional tests for setting the new params
=> Add tests for setting the new params

docs/Overview.md, ethereum/contracts/governance/Governance.sol, ethereum/contracts/upgrades/BaseZkSyncUpgrade.sol, ethereum/contracts/zksync/libraries/LibMap.sol, zksync/contracts/L2ContractHelper.sol
=> Fix documentation mismatch

l2-contracts/src/upgradeBridgeImpl.ts
=> Fix upgrade l2 bridge script

system-contracts/contracts/L1Messenger.sol
=> fix(L1Messenger): validate pubdata before publishing blob hashes

l1-contracts/contracts/zksync/facets/Executor.sol
=> fix(commitBatches): removed unnecessary require

l1-contracts/contracts/zksync/facets/Executor.sol
=> fix(Executor): combined var declaration and assignment

l1-contracts/contracts/zksync/facets/Executor.sol, l1-contracts/test/foundry/unit/concrete/Executor/Committing.t.sol
=> fix(executor): separated require with 2 conditions into 2 statements

system-contracts/SystemContractsHashes.json, system-contracts/bootloader/bootloader.yul, system-contracts/bootloader/tests/bootloader/bootloader_test.yul
=> fix(bootloader): fixed system log key for protocol upgrade txn hash

l2-contracts/package.json, l2-contracts/src/updateL2ERC20Metadata.ts
=> Update l2 ERC-20 metadata script

l1-contracts/contracts/bridge/L1ERC20Bridge.sol
- Correct comments in L1 Erc20 bridge
- nonReentrant where needed
=> Fix hyper comments

system-contracts/SystemContractsHashes.json, system-contracts/contracts/Constants.sol, system-contracts/scripts/preprocess-bootloader.ts
The previous code dedicated a bit too little space for the pubdata (roughly 240kb instead of desired roughly 260kb)
=> Increase the area dedicated to pubdata encoding

l1-contracts/scripts/deploy.ts
This pr breaks the default init, we have to make rebuild the script completely or keep it as is
=> Revert "Fix: early exit in `onlyVerifier` branch"

.github/workflows/build-release-manual.yaml
Workflow for manual contract builds
In case with manual releases instead of build on each commit
=> ci: add workflow for manual build

l1-contracts/src.ts/deploy.ts
BLOB_VERSIONED_HASH_RETRIEVER_ADDR -> CONTRACT_BLOB_VERSIONED_HASH_RETRIEVER_ADDR
Consistency with other names
=> Fix env var name

l1-contracts/scripts/utils.ts, l1-contracts/src.ts/deploy.ts
update deploy to set multiple validator addresses
=> feat(validator): initialize validator timelock with mulitiple addresses

.github/workflows/build-release-manual.yaml, .github/workflows/buld-release.yaml, .github/workflows/l1-contracts-ci.yaml, .github/workflows/l2-contracts-ci.yaml, .github/workflows/nodejs-license.yaml, .github/workflows/system-contracts-ci.yaml
Fix for publish auto releases
It's wrong now and takes from commit
=> ci: fix releases for auto-release workflow

.github/workflows/build-release-manual.yaml, .github/workflows/buld-release.yaml, .github/workflows/l1-contracts-ci.yaml, .github/workflows/l2-contracts-ci.yaml, .github/workflows/nodejs-license.yaml, .github/workflows/system-contracts-ci.yaml
=> ci: fix releases for auto-release workflow (#238)

system-contracts/scripts/utils.ts
=> Use CompilerDownloader to get solc path

l2-contracts/contracts/bridge/L2SharedBridge.sol
=> Kl l2 shared bridge migration fix, allow legacy bridge deposits

l2-contracts/contracts/bridge/L2SharedBridge.sol, l2-contracts/src/deploy-shared-bridge-on-l2-through-l1.ts, l2-contracts/test/erc20.test.ts
=> Kl l2 shared bridge migration fix2

l1-contracts/contracts/state-transition/chain-deps/facets/Executor.sol
=> Fix validiums and hyperchains

.solhint.json, l1-contracts/contracts/dev-contracts/test/DummySharedBridge.sol, l1-contracts/test/foundry/unit/concrete/AddressAliasHelper/applyL1ToL2Alias.t.sol, l1-contracts/test/foundry/unit/concrete/AddressAliasHelper/undoL1ToL2Alias.t.sol, l1-contracts/test/foundry/unit/concrete/Bridgehub/experimental_bridge.t.sol, l1-contracts/test/foundry/unit/concrete/state-transition/libraries/PriorityQueue/PopOperations.sol, l1-contracts/test/foundry/unit/concrete/state-transition/libraries/PriorityQueue/PushOperations.sol, l1-contracts/test/foundry/unit/concrete/state-transition/libraries/PriorityQueue/_PriorityQueue_Shared.t.sol, system-contracts/contracts/test-contracts/KeccakTest.sol
This PR enables explicit type checking using solhint linter.
=> Enable explicit type checking in solhint

docs/Overview.md
=> docs: add l1->l2 filtering explanation

.codespell/.codespellrc, .codespell/wordlist.txt, _typos.toml
The spellcheck for some reasons points to a typo in the PGP pub key
=> Fix spellcheck

system-contracts/SystemContractsHashes.json, system-contracts/bootloader/bootloader.yul
Fix some issues in the `dev` branch
=> Fix several bootloader issues

l1-contracts/contracts/state-transition/StateTransitionManager.sol, l1-contracts/contracts/state-transition/chain-deps/DiamondInit.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Admin.sol, l1-contracts/test/foundry/unit/concrete/DiamondCut/UpgradeLogic.t.sol, l1-contracts/test/unit_tests/proxy_test.spec.ts
=> KL fix OZ L04

l1-contracts/contracts/common/Messaging.sol, l1-contracts/contracts/state-transition/ValidatorTimelock.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Getters.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Mailbox.sol, l1-contracts/test/test_config/constant/hardhat.json
=> Fix oz hyperchain n04

l1-contracts/contracts/state-transition/StateTransitionManager.sol
=> KL OZ fix L01

l1-contracts/contracts/state-transition/chain-deps/facets/Executor.sol
=> Fix OZ hyperchain audit N-07

l1-contracts/contracts/state-transition/StateTransitionManager.sol
=> Audit fix OZ hyperchain N-03

l1-contracts/contracts/state-transition/chain-deps/facets/Executor.sol
=> Kl-fix-oz-hyperchain-l05

l1-contracts/contracts/state-transition/StateTransitionManager.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Executor.sol
=> RA N05 fix typographical errors

l1-contracts/contracts/state-transition/IStateTransitionManager.sol, l1-contracts/contracts/state-transition/StateTransitionManager.sol, l1-contracts/contracts/state-transition/chain-deps/ZkSyncStateTransitionStorage.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Admin.sol, l1-contracts/contracts/state-transition/chain-interfaces/IAdmin.sol
=> Audit fix OZ hyperchain L-06

l1-contracts/contracts/state-transition/StateTransitionManager.sol, l1-contracts/contracts/state-transition/chain-deps/DiamondInit.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Mailbox.sol
=> Audit fix OZ hyperchain N-01

l1-contracts/contracts/state-transition/StateTransitionManager.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Admin.sol
=> OZ hyperchains M01

l1-contracts/contracts/state-transition/ValidatorTimelock.sol, l1-contracts/test/foundry/unit/concrete/ValidatorTimelock/ValidatorTimelock.t.sol
=> Ra N08 indexed params for validator timelock events

l1-contracts/contracts/state-transition/IStateTransitionManager.sol, l1-contracts/contracts/state-transition/StateTransitionManager.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Admin.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Mailbox.sol, l1-contracts/contracts/state-transition/chain-deps/facets/ZkSyncStateTransitionBase.sol, l1-contracts/test/foundry/unit/concrete/state-transition/StateTransitionManager/CreateNewChain.t.sol, l1-contracts/test/foundry/unit/concrete/state-transition/StateTransitionManager/StateTransitionGovernorZero.t.sol, l1-contracts/test/foundry/unit/concrete/state-transition/StateTransitionManager/_StateTransitionManager_Shared.t.sol, l1-contracts/test/foundry/unit/concrete/state-transition/chain-deps/facets/Admin/UpgradeChainFromVersion.t.sol
=> Audit fix OZ hyperchain N-02

system-contracts/contracts/EvmInterpreter.yul
=> Add gas tracking and properly return values instead of relying on the sstore instruction

system-contracts/contracts/EvmInterpreter.yul
This PR adds the `or` and `pushN` instructions.
=> [EVM-Equivalent-YUL] Add `or` and `push` implementation

system-contracts/contracts/EvmInterpreter.yul
This PR adds `div`, `sdiv`, `mod`, `smod` opcodes, as well as some tests for them.
=> [EVM-Equivalent-YUL] Add div, sdiv, mod, smod opcodes

.github/workflows/l1-contracts-foundry-ci.yaml
- Adds CI that deploys the L1 foundry scripts to an anvil instance in order to validate scripts are working correctly.
- To improve resiliance of foundry scripts.
=> feat: add l1 foundry scripts CI

l1-contracts/contracts/state-transition/chain-deps/facets/Executor.sol, system-contracts/bootloader/bootloader.yul, system-contracts/contracts/GasBoundCaller.sol, system-contracts/contracts/L1Messenger.sol, system-contracts/contracts/libraries/SystemContractHelper.sol, system-contracts/contracts/libraries/SystemContractsCaller.sol
=> Fix L-01 issue in OZ VM 1.5.0 audit

system-contracts/bootloader/bootloader.yul, system-contracts/contracts/SystemContext.sol, system-contracts/contracts/libraries/SystemContractHelper.sol
=> Fix L-02 issue in OZ VM 1.5.0 audit

system-contracts/bootloader/bootloader.yul, system-contracts/contracts/GasBoundCaller.sol, system-contracts/contracts/precompiles/CodeOracle.yul
=> Fix N-01 issue in OZ VM 1.5.0 audit

system-contracts/contracts/GasBoundCaller.sol
=> Fix N-02 issue in OZ VM 1.5.0 audit

l1-contracts/package.json, system-contracts/SystemContractsHashes.json, system-contracts/contracts/Constants.sol, system-contracts/contracts/Create2Factory.sol, system-contracts/package.json, system-contracts/scripts/constants.ts, system-contracts/test/Create2Factory.spec.ts, yarn.lock
Add a built-in create2 factory
=> Built-in create2 factory support

l1-contracts/contracts/bridge/L1ERC20Bridge.sol, l1-contracts/contracts/bridge/L1SharedBridge.sol, l1-contracts/contracts/bridge/interfaces/IL1ERC20Bridge.sol, l1-contracts/contracts/bridge/interfaces/IL2Bridge.sol, l1-contracts/contracts/bridgehub/Bridgehub.sol, l1-contracts/contracts/state-transition/ValidatorTimelock.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Mailbox.sol, l1-contracts/contracts/state-transition/chain-interfaces/IMailbox.sol, l1-contracts/contracts/state-transition/chain-interfaces/IZkSyncHyperchain.sol, l1-contracts/contracts/upgrades/BaseZkSyncUpgradeGenesis.sol, l2-contracts/contracts/bridge/L2SharedBridge.sol, l2-contracts/contracts/bridge/interfaces/IL2SharedBridge.sol, system-contracts/SystemContractsHashes.json, system-contracts/contracts/Constants.sol, system-contracts/contracts/DefaultAccount.sol, system-contracts/contracts/L2BaseToken.sol, system-contracts/contracts/interfaces/ISystemContext.sol
- Remove unneeded param
- Fix event
- Fix some comments
- Remove unused events
=> Set of some QA fixes

system-contracts/contracts/EvmInterpreter.yul
This PR adds `gas`, `address`, `pc`, `balance` and `origin` opcodes
=> [EVM-Equivalent-Yul] Add some environment opcodes

system-contracts/contracts/EvmInterpreter.yul
This PR adds `CALLER`, `CALLVALUE`, `CALLDATALOAD`, `CALLDATASIZE`, `CALLDATACOPY` opcodes
=> [EVM-Equivalent-Yul] Add more environment opcodes

system-contracts/contracts/EvmInterpreter.yul
This PR adds code to charge gas on some opcodes which didn't have it.
=> [EVM-Equivalent-Yul] Add gas charge to lacking opcodes

system-contracts/contracts/EvmInterpreter.yul
=> [EVM-Equivalent-YUL] Add environment3 opcodes

system-contracts/contracts/EvmInterpreter.yul
=> Evm yul keccak opcode

l1-contracts/scripts/display-governance.ts, l1-contracts/scripts/initialize-l2-weth-token.ts, l1-contracts/scripts/read-variable.ts, l2-contracts/contracts/Config.sol, l2-contracts/contracts/bridge/L2SharedBridge.sol, l2-contracts/hardhat.config.ts, l2-contracts/package.json, l2-contracts/src/deploy-shared-bridge-on-l2-through-l1.ts, l2-contracts/test/erc20.test.ts, l2-contracts/test/weth.test.ts, system-contracts/package.json, yarn.lock
Removing deprecated solpp dependencies from l2-contracts
=> remove solpp dependencies

system-contracts/contracts/EvmInterpreter.yul
=> [EVM-Equivalent-YUL]  Implement log opcodes

system-contracts/contracts/EvmInterpreter.yul
This PR adds Return, Revert and Invalid opcodes
Tests for this PR are in:
https://github.com/matter-labs/zksync-era/pull/1695
=> [EVM-Equivalent-YUL] System instructions part 3

l1-contracts-foundry/script/DeployErc20.s.sol, yarn.lock
=> chore(scripts): Get Scripts Working in CI

.gitignore, system-contracts/contracts/EvmInterpreter.yul, system-contracts/contracts/EvmInterpreterFunctions.yul, system-contracts/contracts/EvmInterpreterLoop.yul
Adds a preprocessor for EvmInterpreter.yul, it gives the possibility of using includes inside the file
Remember to run `npm install -g preprocess-cli-tool`
Related to the following PR: https://github.com/matter-labs/zksync-era/pull/1730
=> Add preprocessor for evm interpreter

README.md, l1-contracts-foundry/script/DeployErc20.s.sol
Just a small change to try out the CI on the dev branch
=> Debug dev CI

system-contracts/SystemContractsHashes.json, system-contracts/bootloader/bootloader.yul, system-contracts/scripts/preprocess-bootloader.ts
=> Upgrade system context before any operation

l1-contracts/package.json, l1-contracts/scripts/setup-legacy-bridge-era.ts, l2-contracts/src/deploy-shared-bridge-on-l2-through-l1.ts
Several renamings for local tooling for better clarity
=> Rename local legacy bridge setup

l1-contracts/scripts/setup-legacy-bridge-era.ts
=> Fix flaky loadtest

l1-contracts/contracts/bridge/L1SharedBridge.sol, l1-contracts/package.json, l1-contracts/scripts/token-migration.ts, l1-contracts/src.ts/hyperchain-upgrade.ts
=> Script + safeTransferFromLegacy

l1-contracts/contracts/state-transition/StateTransitionManager.sol
=> fix: get all hyperchains

system-contracts/contracts/EvmInterpreterFunctions.template.yul, system-contracts/contracts/EvmInterpreterLoop.template.yul
Fix code in order to execute integration tests successfully.
=> [EVM-Equivalent-YUL] EVM integration tests

system-contracts/contracts/EvmInterpreterFunctions.template.yul, system-contracts/contracts/EvmInterpreterLoop.template.yul
Add gas calculations for `CALL` opcode
=> [EVM-Equivalent-YUL] Evm yul call gas

l1-contracts/contracts/state-transition/chain-deps/facets/Executor.sol
=> chore(executor): remove constraint on pubdata hash for validiums

l1-contracts/src.ts/deploy.ts
=> chore(scripts): update setValidium to setPubdataPricing

l1-contracts/package.json, l1-contracts/scripts/governance-accept-ownership.ts
=> Accept ownership script

system-contracts/contracts/EvmInterpreter.template.yul, system-contracts/contracts/EvmInterpreterFunctions.template.yul, system-contracts/contracts/EvmInterpreterLoop.template.yul
=> [EVM-Equivalence-Yul] Add delegatecall opcode

system-contracts/contracts/EvmInterpreterFunctions.template.yul, system-contracts/contracts/EvmInterpreterLoop.template.yul
=> [EVM-Equivalent-YUL] Evm yul extcodehash

l1-contracts/scripts/upgrade-consistency-checker.ts
=> feat: more checks

system-contracts/SystemContractsHashes.json, system-contracts/bootloader/bootloader.yul, system-contracts/bootloader/test_infra/Cargo.lock, system-contracts/bootloader/test_infra/Cargo.toml, system-contracts/bootloader/test_infra/src/hook.rs, system-contracts/bootloader/test_infra/src/main.rs
=> Extend bootloader memory

system-contracts/contracts/EvmInterpreterLoop.template.yul
This PR fixes gas consumption for codecopy
=> [EVM-Equivalent-YUL] Fix codecopy gas

system-contracts/contracts/EvmInterpreterFunctions.template.yul, system-contracts/contracts/EvmInterpreterLoop.template.yul, system-contracts/contracts/EvmInterpreterPreprocessed.yul, yarn.lock
This PR fixes gas consumption for various opcodes
Its tests are in the following [PR](https://github.com/matter-labs/zksync-era/pull/1832)
=> [EVM-Equivalent-YUL] Various Opcodes gas fixes

l1-contracts/contracts/state-transition/chain-deps/facets/Executor.sol
=> remove log values when validium

l2-contracts/src/deploy-shared-bridge-on-l2-through-l1.ts
Initialisation of chain governance requires calling `executeUpgrade` of the Governance contract which assumes higher level of privileges.
Skipping governance initialisation will allow chain admins to perform deployment of the L2 contracts by themselves while delegating only the last call to the Governor.
=> Allow to skip initialization of chain governance

l1-contracts-foundry/script/AcceptAdmin.s.sol, l1-contracts-foundry/script/RegisterHyperchain.s.sol, l1-contracts-foundry/script/Utils.sol
=> fix init bridges

l2-contracts/contracts/bridge/L2SharedBridge.sol, l2-contracts/contracts/bridge/interfaces/IL2SharedBridge.sol, l2-contracts/contracts/bridge/interfaces/ILegacyL2SharedBridge.sol
=> fix: small changes in the bridge

l1-contracts-foundry/script-config-template/config-deploy-l1.toml, l1-contracts-foundry/script-config-template/register-hyperchain.toml, l1-contracts-foundry/script/DeployL1.s.sol, l1-contracts-foundry/script/RegisterHyperchain.s.sol
- Upgrades foundry scripts with new hyperchain configs
=> feat: update foundry scripts with new config

system-contracts/contracts/EvmInterpreterLoop.template.yul, system-contracts/contracts/EvmInterpreterPreprocessed.yul
This PR makes an optimization on sload opcode
=> [EVM-Equivalence-YUL] Optimize sload

system-contracts/contracts/EvmInterpreterFunctions.template.yul, system-contracts/contracts/EvmInterpreterLoop.template.yul, system-contracts/contracts/EvmInterpreterPreprocessed.yul
This PR makes several optimizations for the evm based on the benchmarks in `era-compiler-tester`
=> [EVM-Equivalence-YUL] Opcode Optimizations

l1-contracts/package.json, l2-contracts/package.json, system-contracts/package.json, yarn.lock
=> Sync release v23 with main

l1-contracts/contracts/bridge/L1SharedBridge.sol, l1-contracts/contracts/state-transition/ValidatorTimelock.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Mailbox.sol, l2-contracts/contracts/bridge/L2SharedBridge.sol
=> Fix audit issue N-01

l1-contracts/contracts/bridgehub/Bridgehub.sol
=> Fix audit issue N-02

l1-contracts/contracts/bridge/L1SharedBridge.sol, l1-contracts/contracts/bridgehub/Bridgehub.sol
=> Fix audit issue L-01

l1-contracts/contracts/bridge/L1SharedBridge.sol, l1-contracts/contracts/bridgehub/Bridgehub.sol
=> Fix audit issue L-02

.github/workflows/l1-contracts-ci.yaml
=> Add CI coverage (reopenned to dev)

l1-contracts/contracts/bridgehub/Bridgehub.sol, l1-contracts/contracts/bridgehub/IMessageRoot.sol, l1-contracts/contracts/bridgehub/ISTMDeploymentTracker.sol, l1-contracts/contracts/bridgehub/MessageRoot.sol, l1-contracts/contracts/bridgehub/STMDeploymentTracker.sol, l1-contracts/contracts/common/Config.sol, l1-contracts/contracts/state-transition/IStateTransitionManager.sol, l1-contracts/contracts/state-transition/StateTransitionManager.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Admin.sol, l1-contracts/contracts/state-transition/chain-interfaces/IAdmin.sol, l1-contracts/scripts/sync-layer.ts, l1-contracts/test/unit_tests/synclayer.spec.ts
=> Some clarification

contracts-review-prep.md, l1-contracts/contracts/bridge/L1AssetRouter.sol, l1-contracts/contracts/bridge/L1ERC20Bridge.sol, l1-contracts/contracts/bridge/L1NativeTokenVault.sol, l1-contracts/contracts/bridge/interfaces/IL1AssetHandler.sol, l1-contracts/contracts/bridge/interfaces/IL1AssetRouter.sol, l1-contracts/contracts/bridge/interfaces/IL1ERC20Bridge.sol, l1-contracts/contracts/bridgehub/Bridgehub.sol, l1-contracts/contracts/bridgehub/MessageRoot.sol, l1-contracts/contracts/bridgehub/STMDeploymentTracker.sol, l1-contracts/hardhat.config.ts, l1-contracts/test/foundry/unit/concrete/Bridges/L1SharedBridge/L1SharedBridgeBase.t.sol, l1-contracts/test/foundry/unit/concrete/Bridges/L1SharedBridge/L1SharedBridgeFails.t.sol, l1-contracts/test/foundry/unit/concrete/Bridges/L1SharedBridge/L1SharedBridgeHyperEnabled.t.sol, l1-contracts/test/foundry/unit/concrete/Bridges/L1SharedBridge/L1SharedBridgeLegacy.t.sol, l1-contracts/test/foundry/unit/concrete/Bridges/L1SharedBridge/_L1SharedBridge_Shared.t.sol
=> chore: merge CAB

l1-contracts/deploy-script-config-template/config-deploy-erc20.toml, l1-contracts/deploy-scripts/DeployErc20.s.sol
Allow minting to multiple addresses
=> feat(deploy): Mint tokens to multiple addresses

gas-bound-caller/package.json, l1-contracts/package.json, l2-contracts/package.json, system-contracts/package.json, yarn.lock
Upgrading `zksync-ethers` from v5 beta to stable.
=> chore: zksync-ethers to stable v5.9.0

CODEOWNERS
=> Make Deniallugo codeowner for deploy scripts

l1-contracts/deploy-scripts/AcceptAdmin.s.sol
=> Accept admin using methods not files

l1-contracts/contracts/state-transition/data-availability/CalldataDA.sol, l1-contracts/test/foundry/unit/concrete/state-transition/data-availability/CalldataDA.t.sol, l1-contracts/test/foundry/unit/concrete/state-transition/data-availability/RelayedSLDAValidator.t.sol
=> add pubdata size check

system-contracts/contracts/EvmInterpreterFunctions.template.yul, system-contracts/contracts/EvmInterpreterPreprocessed.yul
https://forum.openzeppelin.com/t/nonce-of-a-smart-contract-when-transaction-reverts/3418
=> [EVM Equivalence Yul] Increment nonce on failed deployments only for eoas

l1-contracts/contracts/state-transition/chain-deps/facets/Executor.sol, l1-contracts/test/foundry/unit/concrete/Executor/Executing.t.sol, l1-contracts/test/foundry/unit/concrete/Utils/Utils.sol
=> Update execute batches to allow for default before priority tree

l1-contracts/contracts/state-transition/chain-deps/facets/Executor.sol
=> added batch root sending to executor fn

.github/workflows/l1-contracts-ci.yaml
=> add gas test ci for l1 contracts

l1-contracts/contracts/bridge/L1ERC20Bridge.sol, l1-contracts/contracts/bridge/L1SharedBridge.sol, l1-contracts/contracts/common/L1ContractErrors.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Admin.sol, l1-contracts/test/foundry/unit/concrete/Bridges/L1Erc20Bridge/Deposit.t.sol, l1-contracts/test/foundry/unit/concrete/Bridges/L1SharedBridge/L1SharedBridgeFails.t.sol, l1-contracts/test/foundry/unit/concrete/DiamondCut/UpgradeLogic.t.sol, l1-contracts/test/foundry/unit/concrete/state-transition/chain-deps/facets/Admin/UnfreezeDiamond.t.sol, system-contracts/SystemContractsHashes.json, system-contracts/contracts/Compressor.sol, system-contracts/contracts/SystemContractErrors.sol, system-contracts/test/Compressor.spec.ts
=> OZ L-01 Fix Misleading Errors

l1-contracts/contracts/state-transition/StateTransitionManager.sol
=> L-03 getAllHyperchains Function Reverts Due to Invalid Key Access

l1-contracts/contracts/common/L1ContractErrors.sol, system-contracts/SystemContractsHashes.json, system-contracts/contracts/SystemContractErrors.sol
=> N-05 Unused Errors

l1-contracts/contracts/common/L1ContractErrors.sol, l1-contracts/contracts/upgrades/ZkSyncUpgradeErrors.sol, l2-contracts/contracts/errors/L2ContractErrors.sol, system-contracts/SystemContractsHashes.json, system-contracts/contracts/SystemContractErrors.sol
=> N-06 Improved Organization of Error Files

l1-contracts/contracts/common/L1ContractErrors.sol, l2-contracts/contracts/errors/L2ContractErrors.sol
=> N-08 Unnamed Error Parameters

l1-contracts/contracts/common/L1ContractErrors.sol, l1-contracts/contracts/upgrades/BaseZkSyncUpgrade.sol, l1-contracts/contracts/upgrades/BaseZkSyncUpgradeGenesis.sol, l1-contracts/contracts/upgrades/ZkSyncUpgradeErrors.sol
=> N-12 Misplaced Error Declarations

l2-contracts/contracts/TestnetPaymaster.sol
=> N-13 Unused Named Return Variable

l1-contracts/contracts/state-transition/chain-deps/facets/Mailbox.sol, l1-contracts/contracts/vendor/AddressAliasHelper.sol
=> N-16 Risk of Disabling Valid Warnings

l1-contracts/contracts/governance/Governance.sol, l1-contracts/contracts/state-transition/ValidatorTimelock.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Executor.sol, system-contracts/SystemContractsHashes.json, system-contracts/contracts/Compressor.sol
=> N-18 Inconsistent Application of Solhint Rule gas-length-in-loops

l1-contracts/contracts/state-transition/chain-deps/facets/Executor.sol
=> N-19 Duplicate Code

system-contracts/SystemContractsHashes.json, system-contracts/contracts/AccountCodeStorage.sol, system-contracts/contracts/MsgValueSimulator.sol
=> N-20 Overly Exposed State Variable

l1-contracts/contracts/state-transition/chain-interfaces/IMailbox.sol
=> N-24 Lack of Indexed Event Parameters

l1-contracts/contracts/state-transition/chain-deps/facets/Executor.sol, system-contracts/SystemContractsHashes.json, system-contracts/contracts/L1Messenger.sol
=> N-21 Inconsistent Initialization of Local Variables

l1-contracts/contracts/common/ReentrancyGuard.sol, l1-contracts/contracts/upgrades/BaseZkSyncUpgrade.sol, l1-contracts/contracts/upgrades/BaseZkSyncUpgradeGenesis.sol, system-contracts/SystemContractsHashes.json, system-contracts/bootloader/bootloader.yul
=> N-23 Misleading Documentation

l1-contracts/deploy-scripts/AcceptAdmin.s.sol, l1-contracts/deploy-scripts/DeployL1.s.sol, l1-contracts/deploy-scripts/RegisterHyperchain.s.sol, l1-contracts/scripts/register-hyperchain.ts, l1-contracts/src.ts/deploy-process.ts, l1-contracts/src.ts/deploy-test-process.ts, l1-contracts/src.ts/deploy-utils.ts, l1-contracts/src.ts/deploy.ts
Adds chain admin to deploy scripts
Chain admin is deployed in `zk init`
=> Chain admin contract scripts

l2-contracts/contracts/bridge/L2NativeTokenVault.sol
=> (fix): C-01 All Assets Can Be Stolen From the Vault

l1-contracts/contracts/bridge/L1ERC20Bridge.sol, l1-contracts/contracts/bridge/L1SharedBridge.sol, l1-contracts/contracts/bridge/interfaces/IL1ERC20Bridge.sol, l1-contracts/contracts/dev-contracts/DummyL1ERC20Bridge.sol, l1-contracts/contracts/dev-contracts/test/L1ERC20BridgeTest.sol, l1-contracts/src.ts/deploy.ts, l1-contracts/test/foundry/unit/concrete/Bridges/L1Erc20Bridge/_L1Erc20Bridge_Shared.t.sol
=> (fix): H-02 User Funds Can Be Frozen in the L1NativeTokenVault

l2-contracts/contracts/L2ContractHelper.sol, l2-contracts/contracts/bridge/L2NativeTokenVault.sol
=> (fix): M-01 L2 Native Tokens Become Unmintable on Beacon Change

l1-contracts/contracts/bridgehub/Bridgehub.sol, l1-contracts/contracts/bridgehub/IBridgehub.sol
=> (feat): L-01 Lack of Events

l1-contracts/contracts/bridge/L1SharedBridge.sol, l1-contracts/contracts/bridge/interfaces/IL1AssetHandler.sol
=> (fix): L-02 Misleading Value Is Forwarded During Deposit

l1-contracts/contracts/bridge/L1NativeTokenVault.sol, l1-contracts/contracts/bridge/L1SharedBridge.sol, l1-contracts/contracts/bridge/interfaces/IL1NativeTokenVault.sol, l1-contracts/contracts/bridgehub/Bridgehub.sol, l1-contracts/contracts/common/libraries/DataEncoding.sol, l1-contracts/contracts/dev-contracts/test/DummyAdminFacetNoOverlap.sol, l1-contracts/src.ts/utils.ts, l1-contracts/test/foundry/unit/concrete/Bridgehub/experimental_bridge.t.sol, l1-contracts/test/foundry/unit/concrete/Bridges/L1SharedBridge/_L1SharedBridge_Shared.t.sol, l1-contracts/test/unit_tests/l1_shared_bridge_test.spec.ts, l2-contracts/contracts/bridge/L2NativeTokenVault.sol, l2-contracts/contracts/bridge/L2SharedBridge.sol, l2-contracts/contracts/common/libraries/DataEncoding.sol
=> (fix): L-04 Fragile Encodings

l1-contracts/contracts/bridge/L1SharedBridge.sol, l1-contracts/test/unit_tests/custom_base_token.spec.ts, l1-contracts/test/unit_tests/l1_shared_bridge_test.spec.ts, l1-contracts/test/unit_tests/legacy_era_test.spec.ts
=> (fix): L-05 Custom Assets May Not Be Withdrawable

l1-contracts/contracts/bridge/L1NativeTokenVault.sol
=> (fix): L-06 ETH’s L2StandardERC20 Representation Does Not Have name or symbol

l1-contracts/contracts/bridge/L1SharedBridge.sol
=> (fix): L-07 Inaccurate Legacy Deposits Identification

l1-contracts/contracts/bridge/L1NativeTokenVault.sol, l1-contracts/contracts/bridge/L1SharedBridge.sol, l1-contracts/contracts/bridge/interfaces/IL1SharedBridge.sol, l1-contracts/test/foundry/unit/concrete/Bridges/L1SharedBridge/L1SharedBridgeBase.t.sol, l1-contracts/test/foundry/unit/concrete/Bridges/L1SharedBridge/L1SharedBridgeFails.t.sol, l2-contracts/contracts/bridge/L2SharedBridge.sol
=> fix: OZ n 04

l1-contracts/contracts/bridge/L1SharedBridge.sol, l1-contracts/contracts/bridgehub/Bridgehub.sol
=> fix: oz n 05

l2-contracts/contracts/bridge/L2NativeTokenVault.sol, l2-contracts/contracts/bridge/L2SharedBridge.sol
=> fix: OZ n 06

l1-contracts/contracts/bridgehub/Bridgehub.sol, l1-contracts/contracts/bridgehub/STMDeploymentTracker.sol, l1-contracts/contracts/common/Config.sol, l1-contracts/contracts/state-transition/StateTransitionManager.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Admin.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Mailbox.sol, l1-contracts/scripts/sync-layer.ts, l1-contracts/test/foundry/integration/GatewayTests.t.sol, l1-contracts/test/unit_tests/synclayer.spec.ts, l2-contracts/contracts/bridge/L2NativeTokenVault.sol, l2-contracts/test/erc20.test.ts
=> fix: gateway oz c01

l1-contracts/contracts/upgrades/IL1GenesisUpgrade.sol, l1-contracts/contracts/upgrades/L1GenesisUpgrade.sol
=> fix: oz gateway l01

l1-contracts/contracts/bridgehub/STMDeploymentTracker.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Mailbox.sol
=> oz gateway l03

da-contracts/contracts/ValidiumL1DAValidator.sol, l1-contracts/contracts/bridgehub/MessageRoot.sol
=> fix: oz gateway l04

l1-contracts/contracts/common/libraries/FullMerkle.sol
=> wrong order, extra empty nodes in full tree

l1-contracts/contracts/bridgehub/Bridgehub.sol, l1-contracts/contracts/bridgehub/IBridgehub.sol, l1-contracts/contracts/bridgehub/MessageRoot.sol, l1-contracts/contracts/common/libraries/DynamicIncrementalMerkle.sol, l1-contracts/contracts/state-transition/StateTransitionManager.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Executor.sol, system-contracts/SystemContractsHashes.json, system-contracts/contracts/PubdataChunkPublisher.sol
=> fix: gateway l07

da-contracts/contracts/ValidiumL1DAValidator.sol
=> implement erc-165

l2-contracts/contracts/data-availability/RollupL2DAValidator.sol
=> oz gateway l08

l2-contracts/contracts/L2ContractHelper.sol
=> switch the order around

l2-contracts/contracts/data-availability/RollupL2DAValidator.sol, l2-contracts/contracts/data-availability/StateDiffL2DAValidator.sol, l2-contracts/contracts/data-availability/ValidiumL2DAValidator.sol
=> extra solhint removal

l1-contracts/contracts/bridgehub/Bridgehub.sol, l1-contracts/contracts/state-transition/StateTransitionManager.sol, l1-contracts/contracts/state-transition/libraries/PriorityTree.sol
=> extra casts

l1-contracts/contracts/state-transition/chain-deps/facets/Mailbox.sol
=> extra imports

l1-contracts/contracts/bridge/interfaces/IL2Bridge.sol, l1-contracts/contracts/bridge/interfaces/IL2BridgeLegacy.sol, l1-contracts/contracts/bridgehub/IBridgehub.sol, l1-contracts/contracts/bridgehub/IMessageRoot.sol, l1-contracts/contracts/bridgehub/ISTMDeploymentTracker.sol, l1-contracts/contracts/bridgehub/MessageRoot.sol, l1-contracts/contracts/state-transition/l2-deps/IComplexUpgrader.sol, l1-contracts/contracts/state-transition/l2-deps/IL2GenesisUpgrade.sol, l1-contracts/contracts/state-transition/l2-deps/ISystemContext.sol
=> author and security contact

l1-contracts/contracts/common/Config.sol, l1-contracts/contracts/state-transition/chain-interfaces/IAdmin.sol, l2-contracts/contracts/bridge/interfaces/IL2NativeTokenVault.sol, system-contracts/SystemContractsHashes.json, system-contracts/contracts/interfaces/ISystemContract.sol
=> fix: unused imports

l1-contracts/contracts/bridgehub/Bridgehub.sol, l1-contracts/contracts/bridgehub/MessageRoot.sol, l1-contracts/contracts/bridgehub/STMDeploymentTracker.sol, l1-contracts/contracts/common/Config.sol, l1-contracts/contracts/common/L2ContractAddresses.sol, l1-contracts/contracts/common/libraries/FullMerkle.sol, l1-contracts/contracts/common/libraries/MessageHashing.sol, l1-contracts/contracts/common/libraries/Messaging.sol, l1-contracts/contracts/state-transition/StateTransitionManager.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Admin.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Mailbox.sol, l1-contracts/contracts/state-transition/chain-interfaces/IAdmin.sol, l1-contracts/contracts/state-transition/chain-interfaces/IMailbox.sol, l1-contracts/contracts/state-transition/libraries/PriorityTree.sol, l1-contracts/contracts/upgrades/L1GenesisUpgrade.sol, l1-contracts/test/unit_tests/synclayer.spec.ts
=> oz gateway l05

l1-contracts/contracts/state-transition/chain-interfaces/IAdmin.sol, l1-contracts/src.ts/deploy.ts, l2-contracts/contracts/bridge/L2NativeTokenVault.sol, l2-contracts/contracts/bridge/interfaces/IL2NativeTokenVault.sol, l2-contracts/src/deploy-shared-bridge-on-l2-through-l1.ts, l2-contracts/test/erc20.test.ts, system-contracts/contracts/interfaces/ISystemContract.sol
=> update l2  ntv deployment

l1-contracts/contracts/bridgehub/Bridgehub.sol, l1-contracts/contracts/bridgehub/IBridgehub.sol, l1-contracts/contracts/state-transition/IStateTransitionManager.sol, l1-contracts/contracts/state-transition/StateTransitionManager.sol, l1-contracts/contracts/state-transition/chain-deps/ZkSyncHyperchainStorage.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Admin.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Getters.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Mailbox.sol, l1-contracts/contracts/state-transition/chain-interfaces/IAdmin.sol, l1-contracts/contracts/state-transition/chain-interfaces/IGetters.sol, l1-contracts/contracts/state-transition/chain-interfaces/IMailbox.sol, l1-contracts/contracts/state-transition/data-availability/CalldataDA.sol, l1-contracts/deploy-scripts/Gateway.s.sol, l1-contracts/scripts/sync-layer.ts, l1-contracts/src.ts/deploy.ts, l1-contracts/test/foundry/integration/GatewayTests.t.sol, l1-contracts/test/unit_tests/synclayer.spec.ts, l2-contracts/contracts/data-availability/RollupL2DAValidator.sol, l2-contracts/contracts/data-availability/StateDiffL2DAValidator.sol, l2-contracts/contracts/interfaces/IL2DAValidator.sol, system-contracts/SystemContractsHashes.json, system-contracts/contracts/interfaces/IL2DAValidator.sol
=> n10 renamings

da-contracts/contracts/CalldataDA.sol, l1-contracts/contracts/bridgehub/Bridgehub.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Admin.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Executor.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Mailbox.sol, l1-contracts/contracts/state-transition/data-availability/CalldataDA.sol, system-contracts/SystemContractsHashes.json, system-contracts/contracts/PubdataChunkPublisher.sol
=> oz gateway oz n12

l1-contracts/deploy-scripts/AcceptAdmin.s.sol, l1-contracts/scripts/register-hyperchain.ts, l1-contracts/src.ts/deploy.ts, yarn.lock
=> merge main

l1-contracts/contracts/bridgehub/Bridgehub.sol, l1-contracts/contracts/bridgehub/IBridgehub.sol, l1-contracts/contracts/dev-contracts/test/DummyBridgehub.sol, l1-contracts/contracts/dev-contracts/test/DummyBridgehubSetter.sol, l1-contracts/contracts/dev-contracts/test/DummyStateTransitionManager.sol, l1-contracts/contracts/dev-contracts/test/DummyStateTransitionManagerForValidatorTimelock.sol, l1-contracts/contracts/dev-contracts/test/DummyStateTransitionManagerWithBridgeHubAddress.sol, l1-contracts/contracts/state-transition/IStateTransitionManager.sol, l1-contracts/contracts/state-transition/StateTransitionManager.sol, l1-contracts/deploy-scripts/DeployL1.s.sol, l1-contracts/src.ts/deploy.ts, l1-contracts/test/foundry/integration/DeploymentTest.t.sol, l1-contracts/test/foundry/unit/concrete/Bridgehub/experimental_bridge.t.sol, l1-contracts/test/foundry/unit/concrete/state-transition/StateTransitionManager/CreateNewChain.t.sol, l1-contracts/test/foundry/unit/concrete/state-transition/StateTransitionManager/_StateTransitionManager_Shared.t.sol, l1-contracts/test/unit_tests/validator_timelock_test.spec.ts
=> fix: move hyperchain mapping EVM-709

l1-contracts/contracts/dev-contracts/DummyL1ERC20Bridge.sol, l1-contracts/scripts/setup-legacy-bridge-era.ts
=> Fix sync layer stable stable

l2-contracts/contracts/ConsensusRegistry.sol, l2-contracts/contracts/interfaces/IConsensusRegistry.sol, l2-contracts/package.json, l2-contracts/src/deploy-consensus-registry.ts, l2-contracts/src/utils.ts, l2-contracts/test/consensusRegistry.test.ts
https://github.com/matter-labs/era-contracts/pull/555 but merging to main instead of dev.
=> feat(consensus): add L2 registry contract (BFT-434) (#555)

system-contracts/contracts/EvmInterpreter.template.yul, system-contracts/contracts/EvmInterpreterFunctions.template.yul, system-contracts/contracts/EvmInterpreterLoop.template.yul, system-contracts/contracts/EvmInterpreterPreprocessed.yul
This removes calls to mstore8, since they are expensive (this call will be translated to at least 4 instructions).
=> [EVM-Equivalence-YUL] Remove calls to mstore8

l1-contracts/foundry.toml, l1-contracts/remappings.txt, l2-contracts/foundry.toml, system-contracts/foundry.toml
* remappings moved from file to foundry config
* cache path added to all foundry configs
* formatting
=> chore: foundry config cleanup

system-contracts/contracts/EvmInterpreter.template.yul, system-contracts/contracts/EvmInterpreterFunctions.template.yul, system-contracts/contracts/EvmInterpreterLoop.template.yul, system-contracts/contracts/EvmInterpreterPreprocessed.yul
This PR removes the TODOs and FIXMEs from EVM Interpreter
=> [EVM-Equivalence-YUL] Remove TODOs

l1-contracts/contracts/bridge/L1NativeTokenVault.sol, l1-contracts/contracts/bridge/interfaces/IL1AssetHandler.sol, l1-contracts/contracts/bridge/interfaces/IL1BaseTokenAssetHandler.sol, l1-contracts/contracts/bridge/interfaces/IL1NativeTokenVault.sol, l1-contracts/contracts/bridgehub/Bridgehub.sol, l1-contracts/contracts/bridgehub/IBridgehub.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Getters.sol, l1-contracts/deploy-scripts/Gateway.s.sol, l1-contracts/deploy-scripts/Utils.sol, l1-contracts/scripts/register-hyperchain.ts, l1-contracts/src.ts/deploy-utils.ts, l1-contracts/src.ts/deploy.ts, l1-contracts/src.ts/utils.ts, l1-contracts/test/foundry/integration/BridgeHubInvariantTests.t.sol, l1-contracts/test/foundry/integration/BridgehubTests.t.sol, l1-contracts/test/foundry/integration/_SharedHyperchainDeployer.t.sol, l1-contracts/test/foundry/unit/concrete/Bridges/L1SharedBridge/L1SharedBridgeBase.t.sol, l1-contracts/test/foundry/unit/concrete/Bridges/L1SharedBridge/_L1SharedBridge_Shared.t.sol, l1-contracts/test/unit_tests/custom_base_token.spec.ts, l1-contracts/test/unit_tests/utils.ts, l2-contracts/src/deploy-shared-bridge-on-l2-through-l1.ts, l2-contracts/src/utils.ts
=> chore: Kl/merge-stable

system-contracts/contracts/ContractDeployer.sol, system-contracts/contracts/EvmGasManager.sol, system-contracts/contracts/EvmInterpreter.sol, system-contracts/contracts/EvmInterpreter.template.yul, system-contracts/contracts/EvmInterpreterFunctions.template.yul, system-contracts/contracts/EvmInterpreterPreprocessed.yul, system-contracts/contracts/NonceHolder.sol, system-contracts/contracts/interfaces/IContractDeployer.sol, system-contracts/contracts/interfaces/ISystemContract.sol
This PR adds system call modifiers to some system contracts functions to prevent security problems.
=> [EVM-Equivalence-YUL] Restrict functions to only be called from interpreter

l1-contracts/deploy-scripts/DeployL2Contracts.sol, l1-contracts/deploy-scripts/PrepareZKChainRegistrationCalldata.s.sol, l1-contracts/deploy-scripts/Utils.sol, l2-contracts/foundry.toml, l2-contracts/lib/openzeppelin-contracts, l2-contracts/lib/openzeppelin-contracts-upgradeable, l2-contracts/lib/openzeppelin-contracts-upgradeable-v4, l2-contracts/lib/openzeppelin-contracts-v4
=> fix(scrips): read bytecode from foundry not hardhat

l1-contracts/test/foundry/unit/concrete/governance/Governance/AccessControlRestriction.t.sol, l1-contracts/test/foundry/unit/concrete/governance/Governance/ChainAdmin.t.sol
This PR adds tests for ChainAdmin and AccessControlRestriction contracts.
=> Add ChainAdmin and AccessControlRestriction tests

l1-contracts/foundry.toml
Sets optimizer_runs in foundry config to the same value as in hardhat config
More optimizations applied to contracts
=> Set foundry optimizer_runs

l1-contracts/contracts/bridgehub/Bridgehub.sol, l1-contracts/test/foundry/unit/concrete/Bridgehub/experimental_bridge.t.sol
=> Add admin permission to add custom base tokens

l2-contracts/contracts/ConsensusRegistry.sol, l2-contracts/contracts/interfaces/IConsensusRegistry.sol
Needed to make the server work
=> Copy consensus contracts from main

l1-contracts/deploy-scripts/DeployL2Contracts.sol
=> fix(deploy): Initilize chain using ChainAdmin

.github/workflows/build-release.yaml, .github/workflows/l1-contracts-ci.yaml, .github/workflows/l2-contracts-ci.yaml, .github/workflows/slither.yaml, .github/workflows/system-contracts-ci.yaml
Add changes for make CI more readable 
For maintenance
=> ci: make CI more readable

l2-contracts/contracts/ConsensusRegistry.sol, l2-contracts/contracts/interfaces/IConsensusRegistry.sol
Added checks that the validator/attester weights are greater than zero.
Fixes L-02.
=> fix: Missing Validations on Weight

system-contracts/contracts/EvmEmulator.yul, system-contracts/contracts/EvmGasManager.sol, system-contracts/evm-emulator/EvmEmulator.template.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
Created EVM contract should be added to accessed contracts before constructor is called. Also this PR removes additional warm-account calls.
=> fix(EVM): Fix accessed accounts behavior according to EVM

l1-contracts/contracts/bridge/ntv/NativeTokenVault.sol
=> missing chainBalance increase

l1-contracts/contracts/bridge/asset-router/L2AssetRouter.sol, l1-contracts/contracts/bridge/ntv/L2NativeTokenVault.sol
=> fix: kl/m05-2gw more comments

.github/workflows/codespell.yaml, .github/workflows/l1-contracts-ci.yaml, l1-contracts/contracts/bridge/asset-router/L2AssetRouter.sol
=> Fix CI in oz audit sep head

system-contracts/scripts/deploy-preimages.ts
=> fix: Fix bootloader bytecode loading after new `zksolc` version

system-contracts/SystemContractsHashes.json, system-contracts/contracts/KnownCodesStorage.sol
=> fix(EVM): Fix known code storage

system-contracts/SystemContractsHashes.json, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Refactor calls

system-contracts/SystemContractsHashes.json, system-contracts/contracts/EvmEmulator.yul, system-contracts/contracts/EvmEmulator.yul.llvm.options, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> feat(EVM): Compiler based optimizations

l1-contracts/deploy-scripts/ChainConfigurationReader.s.sol
=> feat(zkstack): Show chain info

system-contracts/SystemContractsHashes.json, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> chore(EVM): Simplify system calls in emulator

l1-contracts/contracts/upgrades/BaseZkSyncUpgrade.sol, l1-contracts/contracts/upgrades/ZkSyncUpgradeErrors.sol, system-contracts/SystemContractsHashes.json, system-contracts/contracts/ContractDeployer.sol
=> chore(EVM): Cleanup in contracts

l1-contracts/contracts/state-transition/StateTransitionManager.sol, l1-contracts/contracts/state-transition/l2-deps/AllowedBytecodeTypes.sol, l1-contracts/contracts/state-transition/l2-deps/ISystemContext.sol, l1-contracts/deploy-scripts/PrepareZKChainRegistrationCalldata.s.sol, l1-contracts/deploy-scripts/RegisterHyperchain.s.sol, l1-contracts/scripts/register-hyperchain.ts, l1-contracts/src.ts/deploy-process.ts, l1-contracts/src.ts/deploy.ts, l1-contracts/test/foundry/unit/concrete/Bridgehub/experimental_bridge.t.sol, l1-contracts/test/foundry/unit/concrete/governance/Governance/PermanentRestriction.t.sol, l1-contracts/test/foundry/unit/concrete/state-transition/StateTransitionManager/CreateNewChain.t.sol, l1-contracts/test/foundry/unit/concrete/state-transition/StateTransitionManager/_StateTransitionManager_Shared.t.sol, system-contracts/SystemContractsHashes.json, system-contracts/contracts/ContractDeployer.sol, system-contracts/contracts/SystemContext.sol, system-contracts/contracts/interfaces/IContractDeployer.sol, system-contracts/foundry.toml, system-contracts/test/ContractDeployer.spec.ts
=> fix(EVM): Optional EVM support during chain creation

system-contracts/SystemContractsHashes.json, system-contracts/contracts/EvmGasManager.yul
=> feat(EVM): Simplify warm/cold storage model for "small" slots

system-contracts/SystemContractsHashes.json, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulator.template.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> chore(EVM): Cleanup in emulator

system-contracts/SystemContractsHashes.json, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulator.template.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Panic instead of reverts in case of critical errors

system-contracts/SystemContractsHashes.json, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulator.template.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Fix panics in create/create2

system-contracts/SystemContractsHashes.json, system-contracts/contracts/ContractDeployer.sol, system-contracts/contracts/EvmEmulator.yul, system-contracts/contracts/abstract/SystemContractBase.sol, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Increase deployment nonce for EVM contracts even if creation failed for some reason

system-contracts/SystemContractsHashes.json, system-contracts/contracts/ContractDeployer.sol, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Fix semantic tests

system-contracts/SystemContractsHashes.json, system-contracts/contracts/ContractDeployer.sol, system-contracts/contracts/DefaultAccount.sol, system-contracts/contracts/EvmEmulator.yul, system-contracts/contracts/abstract/SystemContractBase.sol, system-contracts/contracts/libraries/SystemContractHelper.sol, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Prepare fixed CREATE implementation

system-contracts/SystemContractsHashes.json, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> Fix(EVM): Fix keccak gas charge flow

system-contracts/SystemContractsHashes.json, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Fix precompiles gas flow

system-contracts/SystemContractsHashes.json, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Fix ecPairing dynamic gas cost

system-contracts/SystemContractsHashes.json, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Fix gas stipends

system-contracts/SystemContractsHashes.json, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Fix MCOPY gas cost

system-contracts/SystemContractsHashes.json, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Fix EXP gas cost flow

system-contracts/SystemContractsHashes.json, system-contracts/contracts/ContractDeployer.sol, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulator.template.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Make contract creation consistent with Geth implementation

system-contracts/SystemContractsHashes.json, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Fix expand memory

system-contracts/SystemContractsHashes.json, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Update max posible mem to 4 MB

system-contracts/SystemContractsHashes.json, system-contracts/contracts/ContractDeployer.sol
=> fix(EVM): Fix gas in EVM constructor

system-contracts/SystemContractsHashes.json, system-contracts/contracts/Constants.sol, system-contracts/contracts/ContractDeployer.sol, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Fix stipends

system-contracts/contracts/EvmEmulator.yul, system-contracts/contracts/SystemContext.sol, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Cache fixed context values

system-contracts/SystemContractsHashes.json, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> Fix(EVM): Not revert caller frame in CREATE if balance insufficient

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Fix stipend for transfers

l1-contracts/contracts/upgrades/GatewayUpgrade.sol
=> Fix library M-01

l1-contracts/contracts/upgrades/GatewayUpgrade.sol
=> Fix library L-01

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/drafted/EvmEmulatorModexpGas.template.yul
=> fix(EVM): Remove gas calculation logic for unsupported precompiles; draft modexp gas model

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fea(EVM): Optimize JUMP gas charge

system-contracts/SystemContractsHashes.json, system-contracts/contracts/Constants.sol, system-contracts/contracts/ContractDeployer.sol, system-contracts/contracts/DefaultAccount.sol, system-contracts/contracts/EvmEmulator.yul, system-contracts/contracts/SystemContractErrors.sol, system-contracts/contracts/libraries/Utils.sol, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> chore(EVM): Cleanup

system-contracts/SystemContractsHashes.json, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulator.template.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Fix emulator memory layout

system-contracts/SystemContractsHashes.json, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul, system-contracts/package.json
=> fix(EVM): Fx SSTORE gas model

system-contracts/SystemContractsHashes.json, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> feat(EVM): Optimize EXTCODEHASH

system-contracts/SystemContractsHashes.json, system-contracts/contracts/KnownCodesStorage.sol, system-contracts/contracts/libraries/Utils.sol
=> fix(EVM): Fix TODOs in KnownCodesStorage

docs/l2_system_contracts/system_contracts_bootloader_description.md, docs/settlement_contracts/data_availability/standard_pubdata_format.md, docs/settlement_contracts/priority_queue/priority-queue.md, docs/upgrade_history/gateway_upgrade/upgrade_process.md
=> Fix some links

system-contracts/contracts/EvmGasManager.yul
=> fix(EVM): Fix TODOs in EvmGasManager

system-contracts/SystemContractsHashes.json, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Fix zknative calls

system-contracts/SystemContractsHashes.json
=> chore(EVM): Update hashes

system-contracts/SystemContractsHashes.json, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul, system-contracts/evm-emulator/EvmEmulatorLoopUnusedOpcodes.template.yul
=> fix(EVM): Fix panics on invalid opcodes

docs/README.md, l1-contracts/contracts/state-transition/ChainTypeManager.sol, l1-contracts/contracts/state-transition/IChainTypeManager.sol, l1-contracts/contracts/state-transition/L1StateTransitionErrors.sol
=> Delete unused function

system-contracts/foundry.toml, system-contracts/lib/openzeppelin-contracts, system-contracts/lib/openzeppelin-contracts-upgradeable, system-contracts/lib/openzeppelin-contracts-upgradeable-v4, system-contracts/lib/openzeppelin-contracts-v4
fixes oz link for system contracts
to be able to compile with foundry
=> fix: oz link for system contracts

system-contracts/contracts/EvmEmulator.yul, system-contracts/contracts/EvmGasManager.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Implement resetEVMFrame function

system-contracts/contracts/Constants.sol, system-contracts/contracts/ContractDeployer.sol, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulator.template.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Change gas model

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
We do not need to clear all used memory upfront, only unused bytes
=> feat(EVM): Optimize extcodecopy

system-contracts/foundry.toml
=> chore(EVM): Suppress sendtransfer zksolc error

l1-contracts/deploy-scripts/Utils.sol, l1-contracts/deploy-scripts/dev/SetupLegacyBridge.s.sol, system-contracts/foundry.toml
- Suppressed `sendtransfer` zksolc errors in system-contracts
- Fixed openzeppelin import paths in l1-contracts deployment scripts
- Removed unused `getBatchBootloaderBytecodeHash` function
=> chore: Tooling fixes in contracts

.github/workflows/system-contracts-ci.yaml, system-contracts/SystemContractsHashes.json, system-contracts/package.json, system-contracts/scripts/calculate-hashes.ts
=> readd hash check

l2-contracts/foundry.toml, l2-contracts/hardhat.config.ts, system-contracts/SystemContractsHashes.json, system-contracts/foundry.toml, system-contracts/hardhat.config.ts, system-contracts/scripts/compile-yul.ts, system-contracts/scripts/compile-zasm.ts
=> feat: Bump zksolc to 1.5.7

l2-contracts/foundry.toml, l2-contracts/hardhat.config.ts, system-contracts/SystemContractsHashes.json, system-contracts/foundry.toml, system-contracts/hardhat.config.ts, system-contracts/scripts/compile-yul.ts, system-contracts/scripts/compile-zasm.ts
=> chore(EVM): Merge dev

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Add static MCOPY cost

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Cleanup in checkMemIsAccessible

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Add stack overflow check in dupStackItem

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Simplify OP_PC

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Do not charge additionally for EraVM decommit

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Fix stack overflow check

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Fix SSTORE warmth check

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Fix insufficient balance panics

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Wrap access to calldata to prevent out-of-bounds EraVM panic

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Zero out frame gas for underpaid precompiles

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Erase returndatapointer if CREATE failed

system-contracts/SystemContractsHashes.json, system-contracts/contracts/DefaultAccount.sol
=> fix(EVM): Change deploy flow for EIP712 transactions

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Fix panics on insufficient balance in calls

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Fix DUP1 underflow check

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Do not check memory boundaries if size is zero

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fi(EVM): Fix EXTCODECOPY zeroing offset

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Cleanup address bytes in EXTCODECOPY

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Use raw calls to precompiles

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Make DELEGATECALL behavior closer to EVM (2)

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Make DELEGATECALL behavior closer to EVM (3)

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Handle corner case of KECCAK with 0 size

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Increase max allowed memory

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Make fetchDeployedCode more robust (2)

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
Current implementation in AccountCodeStorage differs from EVM specs
=> fix(EVM): Implement EXTCODEHASH in emulator

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Add stipends for calls to zkVM contracts

system-contracts/contracts/ContractDeployer.sol, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Make CREATE flow equivalent to EVM

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Fix LOGs implementation

system-contracts/SystemContractsHashes.json, system-contracts/contracts/DefaultAccount.sol
=> feat(EVM): Remove reserved field usage for EVM deploy using custom txs

system-contracts/SystemContractsHashes.json, system-contracts/contracts/ContractDeployer.sol, system-contracts/contracts/interfaces/IContractDeployer.sol
=> feat(EVM): Return evm gas used in external create methods

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Treat 0x00 as empty account

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Fix logs implementation (2)

l1-contracts/deploy-scripts/DeployL1.s.sol
=> fix(EVM): Fix dev merge artifact

l1-contracts/deploy-scripts/RegisterHyperchain.s.sol
=> fix(EVM): Fx l1 foundry deploy scripts

l1-contracts/deploy-scripts/DeployL1.s.sol
=> fix(EVM) Fix config parsing in L1 foundry deploy script

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
It is cleaner and more efficient to truncate by actual bytecode length.
=> fix(EVM): Simplify and optimize out-of-bounds truncation in `CODECOPY`

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Fix and simplify memory expansion checks

system-contracts/contracts/EvmGasManager.yul
=> fix(EVM): Fix access errors in EvmGasManager (L-02, L-06)

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Replace hardcoded memory offsets (N-01)

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Fix misleading comment (N-03)

system-contracts/contracts/EvmEmulator.yul, system-contracts/contracts/precompiles/CodeOracle.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Gas optimizations (N-04)

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Remove deadcode (N-06)

l1-contracts/contracts/state-transition/chain-deps/facets/Executor.sol, system-contracts/contracts/Constants.sol, system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
=> fix(EVM): Code simplification (N-05)

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulator.template.yul
=> fix(EVM): Remove redundant warming of EVM account during construction (N-12)

system-contracts/contracts/ContractDeployer.sol
=> fix(EVM): Add functionality for force EVM deploys (L-04)

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulator.template.yul
=> fix(EVM): Check the bytecode length on call (L-05)

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Change additional stipends for calls to empty contracts (M-03)

system-contracts/contracts/EvmEmulator.yul, system-contracts/contracts/precompiles/CodeOracle.yul, system-contracts/evm-emulator/EvmEmulator.template.yul
=> fix(EVM): Simplify padding (H-05)

system-contracts/contracts/ContractDeployer.sol
=> fix(EVM): Increment nonce after EVM force deploy (L-04)

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul, system-contracts/evm-emulator/calldata-opcodes/RuntimeScope.template.yul
=> fix(EVM): Use stricter checks for calldata (M-06, M-07)

.github/workflows/l1-contracts-ci.yaml
=> chore: Fix l1 coverage in sync layer stable

system-contracts/contracts/L2GatewayUpgrade.sol, system-contracts/test/DefaultAccount.spec.ts
=> Remove mandatory upgrade for weth (OZ)

l1-contracts/contracts/state-transition/chain-deps/facets/Mailbox.sol
=> fix(EVM): Update Mailbox after merge with Gateway

l1-contracts/deploy-scripts/EnableEvmEmulator.s.sol, system-contracts/contracts/Constants.sol, system-contracts/contracts/ContractDeployer.sol, system-contracts/contracts/EvmPredeploysManager.sol, system-contracts/contracts/SystemContractErrors.sol
Keyless transactions may not work with EVM emulator (due to different gas limit). This PR allows forcefully deploy several important widely used contracts.
=> feat(EVM): Add predeploy mechanics

AllContractsHashes.json, system-contracts/contracts/L2GatewayUpgrade.sol, system-contracts/test/DefaultAccount.spec.ts
=> remove the upgrade for l2 wrapped base token

l1-contracts/contracts/upgrades/L1GatewayBase.sol
=> Fix token fetching

system-contracts/contracts/ContractDeployer.sol
=> fix(EVM): Fix natspecs in ContractDeployer

l1-contracts/contracts/state-transition/verifiers/DualVerifier.sol, l2-contracts/contracts/verifiers/DualVerifier.sol
=> fix: Add comment to verificationKeyHash() (L-01)

l1-contracts/contracts/state-transition/verifiers/DualVerifier.sol, l1-contracts/contracts/state-transition/verifiers/VerifierFflonk.sol, l2-contracts/contracts/verifiers/DualVerifier.sol, l2-contracts/contracts/verifiers/VerifierFflonk.sol, tools/data/fflonk_verifier_contract_template.txt
=> fix: Fix comments in verifiers (N-03)

l1-contracts/test/foundry/l2/unit/GatewayCTMDeployer/GatewayCTMDeployer.t.sol
=> chore: Uncomment test for CTM deployer

l1-contracts/deploy-scripts/GatewayCTMDeployerHelper.sol
=> fix: Add deps for verifiers in Gateway CTM deploy from L1

l1-contracts/foundry.toml
=> chore: Remove node modules from foundry toml in l1

l1-contracts/contracts/state-transition/chain-interfaces/IMailbox.sol
=> kl: oz jan l01 extra comment

l1-contracts/contracts/bridgehub/Bridgehub.sol
=> kl/oz-25jan l02 onlyL1

l1-contracts/contracts/bridge/asset-router/AssetRouterBase.sol
=> Fix OZ N01: unnecessary cast

l1-contracts/contracts/common/libraries/L2ContractHelper.sol
=> Fix OZ N02: add comment

l1-contracts/contracts/bridge/ntv/L2NativeTokenVault.sol, l1-contracts/contracts/governance/L2AdminFactory.sol, l1-contracts/contracts/governance/TransitionaryOwner.sol, l1-contracts/contracts/state-transition/chain-interfaces/IGetters.sol, l1-contracts/contracts/state-transition/libraries/PriorityTree.sol, system-contracts/contracts/interfaces/IL2GenesisUpgrade.sol
=> Fix OZ dec N03: typos

l1-contracts/contracts/bridge/L1Nullifier.sol, l1-contracts/contracts/bridge/asset-router/L1AssetRouter.sol, l1-contracts/contracts/bridge/asset-router/L2AssetRouter.sol, l1-contracts/contracts/bridge/ntv/INativeTokenVault.sol, l1-contracts/contracts/bridge/ntv/NativeTokenVault.sol
=> Fix OZ N06 Remove code duplication

l1-contracts/contracts/bridgehub/Bridgehub.sol
=> Fix OZ N07: fix duplicate imports

da-contracts/contracts/DAContractsErrors.sol, l1-contracts/contracts/bridgehub/CTMDeploymentTracker.sol, l1-contracts/contracts/bridgehub/L1BridgehubErrors.sol, l1-contracts/contracts/common/L1ContractErrors.sol, l1-contracts/contracts/state-transition/chain-deps/facets/ZKChainBase.sol, l1-contracts/contracts/upgrades/BaseZkSyncUpgrade.sol, l1-contracts/contracts/upgrades/ZkSyncUpgradeErrors.sol, l1-contracts/scripts/errors-lint.ts, l1-contracts/test/foundry/l1/unit/concrete/Governance/PermanentRestriction.t.sol, l1-contracts/test/foundry/l1/unit/concrete/state-transition/libraries/TransactionValidator/ValidateL1L2Tx.t.sol, l2-contracts/contracts/errors/L2ContractErrors.sol, system-contracts/contracts/SystemContractErrors.sol
=> Fix OZ N08: Remove unused errors + improve ci for them

l1-contracts/contracts/bridge/asset-router/L1AssetRouter.sol, l1-contracts/contracts/bridge/ntv/L2NativeTokenVault.sol, l1-contracts/contracts/common/L1ContractErrors.sol, l1-contracts/contracts/upgrades/GatewayUpgrade.sol, l1-contracts/contracts/upgrades/L1FixedForceDeploymentsHelper.sol, l1-contracts/contracts/upgrades/L1GenesisUpgrade.sol, l1-contracts/test/foundry/l1/integration/l2-tests-in-l1-context/L2NativeTokenVaultTestAbstract.t.sol, l1-contracts/test/foundry/l1/unit/concrete/Bridges/L1SharedBridge/L1SharedBridgeFails.t.sol, l1-contracts/test/foundry/l1/unit/concrete/upgrades/L1GatewayBase.t.sol, system-contracts/contracts/L2GatewayUpgrade.sol, system-contracts/contracts/L2GenesisForceDeploymentsHelper.sol, system-contracts/contracts/L2GenesisUpgrade.sol
=> Fix OZ dec N09

l1-contracts/contracts/bridge/L1ERC20Bridge.sol, l1-contracts/contracts/common/L2ContractAddresses.sol, l1-contracts/contracts/common/libraries/Merkle.sol, l1-contracts/contracts/state-transition/chain-interfaces/IMailbox.sol
=> Fix CI in oz dec audit base

system-contracts/contracts/precompiles/EcAdd.yul, system-contracts/contracts/precompiles/EcMul.yul, system-contracts/contracts/precompiles/EcPairing.yul, system-contracts/contracts/precompiles/Modexp.yul
Updated gas cost for precompiles based on the geometry.
=> chore: updated gas costs for precompiles

l1-contracts/deploy-scripts/DeployL1.s.sol, l1-contracts/deploy-scripts/DeployUtils.s.sol, l1-contracts/deploy-scripts/Utils.sol, l1-contracts/deploy-scripts/upgrade/EcosystemUpgrade.s.sol, l1-contracts/test/foundry/l1/integration/AssetRouterTest.t.sol, l1-contracts/test/foundry/l1/integration/UpgradeTest.t.sol, l1-contracts/test/foundry/l1/integration/_SharedL1ContractDeployer.t.sol, l1-contracts/test/foundry/l1/integration/l2-tests-in-l1-context/_SharedL2ContractL1DeployerUtils.sol, l1-contracts/test/foundry/l1/unit/concrete/Bridges/L1SharedBridge/L1SharedBridgeFails.t.sol
=> chore: some script refactoring

l1-contracts/deploy-scripts/DeployL2Contracts.sol
Add script to deploy l2 da validator
Needed for this PR https://github.com/matter-labs/zksync-era/pull/3642
In short, we want to extend the zkstack cli tool to add a command to deploy l2 da validator.
This will be usefull for already running chain that are looking to either setup DA or change DA.
=> feat(zkstack_cli): Support deploying l2 DA verifier feature

l1-contracts/foundry.toml
=> chore: merge dev in v27

AllContractsHashes.json, l1-contracts/contracts/state-transition/ChainTypeManager.sol, l1-contracts/contracts/state-transition/IChainTypeManager.sol
=> feat(server-notifier): server notifier v27

l1-contracts/deploy-scripts/upgrade/EcosystemUpgrade.s.sol, l1-contracts/deploy-scripts/upgrade/UpgradeLocalDevnet.s.sol, l1-contracts/upgrade-envs/devnet-era.toml, l1-contracts/upgrade-envs/devnet.toml
=> fix: Fix local upgrade script

l1-contracts/contracts/state-transition/chain-deps/GatewayCTMDeployer.sol, l1-contracts/deploy-scripts/DeployL1.s.sol, l1-contracts/deploy-scripts/DeployUtils.s.sol, l1-contracts/deploy-scripts/GatewayCTMDeployerHelper.sol, l1-contracts/deploy-scripts/GatewayCTMFromL1.s.sol, l1-contracts/deploy-scripts/RegisterZKChain.s.sol, l1-contracts/deploy-scripts/Utils.sol, l1-contracts/test/foundry/l2/unit/GatewayCTMDeployer/GatewayCTMDeployer.t.sol
=> add proxy suffix to server notifier

l1-contracts/deploy-scripts/AcceptAdmin.s.sol
Extends the AcceptAdmin script to be able to set the pubdata_pricing_mode function.
For the zkstack cli to be able to switch DA mode.
=> feat(zkstack_cli): Support set pubdata pricing mode

AllContractsHashes.json, l1-contracts/contracts/state-transition/ChainTypeManager.sol
=> fix: onlyOwnerOrAdmin

l1-contracts/deploy-scripts/upgrade/EcosystemUpgrade.s.sol
set diamond proxy address to pass correct data to constructors.
=> set diamond proxy address 

l1-contracts/upgrade-envs/v0.27.0-evm/stage.toml
Set correct protocol upgrade handler address for stage.
=> update protocol uprade handler stage

l1-contracts/deploy-scripts/upgrade/EcosystemUpgrade.s.sol, l1-contracts/upgrade-envs/v0.27.0-evm/mainnet.toml, l1-contracts/upgrade-envs/v0.27.0-evm/stage.toml, l1-contracts/upgrade-envs/v0.27.0-evm/testnet.toml
Co-authored-by: mm-zk <mm@matterlabs.dev>
=> fix: rollup da manager call

AllContractsHashes.json, recompute_hashes.sh
chore: updated hashes & added script for hash recomputation.
=> chore: updated hashes & added script

AllContractsHashes.json
Updating contract hashes after the merge.
=> updated contract hashes

l1-contracts/deploy-scripts/upgrade/FinalizeUpgrade.s.sol
Not related to v26, but v27 is used in zksync-era, so I do it here
=> Make stage2 finalization of v26 script more efficient

docs/README.md, docs/evm_emulation/differences_from_cancun_evm.md, docs/evm_emulation/evm_gas_emulation.md, docs/evm_emulation/evm_predeploys_list.md, docs/evm_emulation/overview.md, docs/evm_emulation/technical_overview.md
=> chore: Add docs for the EVM emulator

.github/workflows/invariant-tests.yaml, .github/workflows/l1-contracts-ci.yaml
=> Sync release v26 1 with main

l1-contracts/deploy-scripts/DeployUtils.s.sol, l1-contracts/deploy-scripts/upgrade/EcosystemUpgrade.s.sol
=> fix: Fix new chain creation params generation for the upgrade

system-contracts/contracts/precompiles/EcAdd.yul, system-contracts/contracts/precompiles/EcMul.yul, system-contracts/contracts/precompiles/EcPairing.yul, system-contracts/contracts/precompiles/Modexp.yul
=> N-02: Missing or Misleading Documentation

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Fix shadowing in mloadPotentiallyPaddedValue (H-01) 

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Add comments about limited exponent size (L-04)

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Fix variable naming (N-11)

system-contracts/contracts/interfaces/IContractDeployer.sol
=> fix(nonces): explicitly deprecate arbitrary nonce ordering (L-02)

system-contracts/contracts/NonceHolder.sol, system-contracts/contracts/SystemContractErrors.sol
=> fix(nonces): validate nonce value to increase by (L-03)

system-contracts/contracts/interfaces/INonceHolder.sol
=> fix: remove unused event (N-08)

system-contracts/contracts/interfaces/IContractDeployer.sol, system-contracts/contracts/interfaces/INonceHolder.sol
=> fix: make interfaces consistent with implementation (N-03)

system-contracts/contracts/NonceHolder.sol
=> fix: explicit casting (N-10)

system-contracts/contracts/ContractDeployer.sol, system-contracts/contracts/NonceHolder.sol
=> fix: remove redundant returns (N-09)

system-contracts/contracts/NonceHolder.sol
=> fix: more consistent handling of nonce values (N-04)

system-contracts/contracts/EvmEmulator.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul
=> fix(EVM): Fix shifts in modexp gas calculation (C-01)

AllContractsHashes.json, l2-contracts/contracts/ConsensusRegistry.sol, l2-contracts/contracts/interfaces/IConsensusRegistry.sol, l2-contracts/test/consensusRegistry.test.ts
=> chore: Merge main in release 27

AllContractsHashes.json, l1-contracts/contracts/dev-contracts/test/CustomUpgradeTest.sol, l1-contracts/contracts/upgrades/BaseZkSyncUpgrade.sol, l1-contracts/contracts/upgrades/BaseZkSyncUpgradeGenesis.sol, l1-contracts/contracts/upgrades/ZkSyncUpgradeErrors.sol
Ensure that default upgrade is compatible with chains that migrated to another settlement layer (ZK Gateway)
=> Fix default upgrade v28

l1-contracts/test/foundry/l1/unit/concrete/Bridgehub/L2MessageVerification.t.sol, system-contracts/bootloader/bootloader.yul, system-contracts/bootloader/test_infra/Cargo.lock, system-contracts/bootloader/test_infra/Cargo.toml
=> add number of roots

AllContractsHashes.json, system-contracts/contracts/SystemContext.sol, system-contracts/test/SystemContext.spec.ts
=> feat: allow l2 block timestamp to stay same

l1-contracts/test/foundry/l1/integration/L1GatewayTests.t.sol
Test for the previous DefaultUpgrade patch
=> Add test for the default upgrade with gateway

l1-contracts/package.json
=> feat: add fast building

.github/workflows/dead-links.yaml
The [dead links workflow](https://github.com/matter-labs/era-contracts/blob/main/.github/workflows/dead-links.yaml) has been constantly failing recently due to `Too many requests`. This PR fixes this issue by caching, limited concurrency, and retry timing to improve reliability. This comes at the cost of burning more minutes than before, but can be a better alternative to #1463.
=> Fix dead links CI

l1-contracts/README.md, system-contracts/.gitignore, system-contracts/README.md, system-contracts/package.json
- Fix the `test:bootloader` script
- Fix instructions on how to run tests
=> Fix instructions on how to run tests

scripts/unify_and_clean_imports.py
Currently some of our .sol files have messy imports. Some are duplicated in the symbols they import, some are duplicated in the file the import is coming from.
The script introduced in this PR is brought to life to battle that and clean the imports throughout our codebase.
=> chore: Add the script to clean imports 

l1-contracts/contracts/bridgehub/L2MessageVerification.sol, l1-contracts/contracts/bridgehub/MessageRoot.sol, l1-contracts/contracts/common/libraries/MessageHashing.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Executor.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Mailbox.sol, system-contracts/bootloader/bootloader.yul
Modify the code to respond to the comments from review.
=> Address issues from review

system-contracts/contracts/precompiles/CodeOracle.yul
We can just shrink and forward pointer, without additional copying
=> feat(V29): Do not copy bytecode in CodeOracle

AllContractsHashes.json, l2-contracts/contracts/interfaces/IConsensusRegistry.sol, l2-contracts/contracts/interfaces/IContractDeployer.sol
=> fix: slither issue fix

AllContractsHashes.json, system-contracts/bootloader/bootloader.yul
=> fix(v29): fix INTEROP_ROOT_SLOT_SIZE (L-04)

system-contracts/contracts/AccountCodeStorage.sol, system-contracts/contracts/Constants.sol, system-contracts/contracts/ContractDeployer.sol, system-contracts/contracts/EvmEmulator.yul, system-contracts/contracts/EvmGasManager.yul, system-contracts/contracts/libraries/Utils.sol, system-contracts/contracts/precompiles/CodeOracle.yul, system-contracts/evm-emulator/EvmEmulatorFunctions.template.yul, system-contracts/evm-emulator/EvmEmulatorLoop.template.yul
Instead of `0x0202` hash we'll be using `0x0302`.
=> fix: Switch hash type to start with 3

l1-contracts/contracts/common/Messaging.sol, l1-contracts/contracts/interop/IInteropCenter.sol, l1-contracts/contracts/interop/InteropCenter.sol, l1-contracts/contracts/interop/InteropHandler.sol
Cleaning up the interop folder for internal security review.
=> chore: small cleanup of interop folder

AllContractsHashes.json, l2-contracts/contracts/ConsensusRegistry.sol, l2-contracts/contracts/interfaces/IConsensusRegistry.sol
To not risk overflow, we increased the type size.
=> refactor: change validator weight type to u256

AllContractsHashes.json, l1-contracts/contracts/governance/ServerNotifier.sol, system-contracts/bootloader/bootloader.yul, system-contracts/contracts/libraries/SystemContractHelper.sol
Fix for N-08 issue from OZ v29 audit.
=> fix(v29): Typo fixes (N-08)

AllContractsHashes.json, l1-contracts/contracts/common/l2-helpers/IL2ToL1Messenger.sol
Fix for N-07 issue from OZ v29 audit.
=> fix(v29): IL2ToL1Messenger interface fix (N-07)

AllContractsHashes.json, l1-contracts/contracts/state-transition/IValidatorTimelock.sol, l1-contracts/contracts/state-transition/ValidatorTimelock.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Executor.sol, l1-contracts/contracts/state-transition/chain-interfaces/IExecutor.sol, l1-contracts/test/foundry/l1/unit/concrete/Executor/Precommitting.t.sol, system-contracts/bootloader/bootloader.yul
=> fix(v29): code quality improvements (N-05)

AllContractsHashes.json, system-contracts/bootloader/bootloader.yul, system-contracts/contracts/L2InteropRootStorage.sol
=> fix(v29): fix typos (N-04)

l1-contracts/contracts/bridgehub/Bridgehub.sol, l1-contracts/contracts/dev-contracts/test/TestExecutor.sol, l1-contracts/contracts/state-transition/L1StateTransitionErrors.sol, l1-contracts/contracts/state-transition/chain-deps/DiamondInit.sol, l1-contracts/contracts/state-transition/chain-deps/ZKChainStorage.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Admin.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Getters.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Mailbox.sol, l1-contracts/contracts/state-transition/chain-deps/facets/ZKChainBase.sol, l1-contracts/contracts/upgrades/GatewayUpgrade.sol, l1-contracts/contracts/upgrades/L1V29Upgrade.sol, l1-contracts/test/foundry/l1/unit/concrete/Executor/Executing.t.sol, l1-contracts/test/foundry/l1/upgrades/L1V29Upgrade.t.sol, system-contracts/bootloader/bootloader.yul
=> fix(v29): remove unused and redundant code (L-03)

AllContractsHashes.json, system-contracts/bootloader/bootloader.yul
=> fix(v29): revert if incorrect interop root block number (M-01)

AllContractsHashes.json, l2-contracts/contracts/ConsensusRegistry.sol, l2-contracts/contracts/interfaces/IConsensusRegistry.sol, l2-contracts/contracts/interfaces/IContractDeployer.sol, l2-contracts/test/consensusRegistry.test.ts
=> chore: add consensus registry changes to v29

l1-contracts/contracts/state-transition/verifiers/DualVerifier.sol
allow mock verifier on sepolia testnet
to use it on zksync-os-stage
=> allow mock verifier on sepolia testnet

l1-contracts/contracts/bridge/asset-tracker/L2AssetTracker.sol, l1-contracts/contracts/bridgehub/MessageRoot.sol, l1-contracts/contracts/common/MessageVerification.sol, l1-contracts/contracts/common/interfaces/IMessageVerification.sol, l1-contracts/contracts/common/libraries/DataEncoding.sol, l1-contracts/contracts/interop/InteropHandler.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Admin.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Mailbox.sol, l1-contracts/contracts/upgrades/L1V30Upgrade.sol
=> forgot to switch branches locally, so another PR from same branch

AllContractsHashes.json, l1-contracts/contracts/state-transition/chain-deps/facets/Mailbox.sol, l1-contracts/contracts/state-transition/chain-interfaces/IMailboxImpl.sol, system-contracts/contracts/abstract/SystemContractBase.sol
=> add NewPriorityRequestId

l1-contracts/contracts/common/Config.sol, l1-contracts/contracts/common/L1ContractErrors.sol, l1-contracts/contracts/l2-upgrades/L2GenesisForceDeploymentsHelper.sol, l1-contracts/contracts/state-transition/chain-deps/DiamondInit.sol, l1-contracts/contracts/state-transition/chain-deps/ZKChainStorage.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Executor.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Mailbox.sol, l1-contracts/contracts/state-transition/chain-deps/facets/ZKChainBase.sol, l1-contracts/contracts/state-transition/chain-interfaces/IExecutor.sol, l1-contracts/contracts/state-transition/libraries/BatchDecoder.sol, l1-contracts/contracts/state-transition/libraries/TransactionValidator.sol, l1-contracts/contracts/upgrades/BaseZkSyncUpgrade.sol, l1-contracts/contracts/upgrades/L1GenesisUpgrade.sol, l1-contracts/test/foundry/l1/unit/concrete/state-transition/libraries/TransactionValidator/ValidateL1L2Tx.t.sol, l1-contracts/test/foundry/l1/unit/concrete/state-transition/libraries/TransactionValidator/_TransactionValidator_Shared.t.sol
=> fix: small fixes/improvements

l1-contracts/deploy-scripts/upgrade/DefaultEcosystemUpgrade.s.sol
Providing the right bytecode as factory deps for ProxyAdmin.
Not the right bytecode deployed as factory deps to GW.
=> feat: add correct bytecode for ProxyAdmin

l1-contracts/test/foundry/l1/integration/UpgradeTestv29.t.sol
ai: Implement UpgradeIntegrationTest for Ecosystem and Chain upgrades in stage environment
=> add back deleted test,

l1-contracts/deploy-scripts/DeployCTM.s.sol
=> fix getUpgradeAddedFacetCuts

l1-contracts/test/foundry/l1/integration/AssetTrackerTest.t.sol
=> fix 2 small issues in AT tests

l1-contracts/contracts/bridge/asset-tracker/AssetTrackerBase.sol, l1-contracts/contracts/bridge/asset-tracker/AssetTrackerErrors.sol, l1-contracts/contracts/bridge/asset-tracker/GWAssetTracker.sol, l1-contracts/contracts/bridge/asset-tracker/IGWAssetTracker.sol, l1-contracts/contracts/bridge/asset-tracker/L1AssetTracker.sol, l1-contracts/contracts/bridge/asset-tracker/LegacySharedBridgeAddresses.sol, l1-contracts/contracts/bridgehub/IMessageRoot.sol, l1-contracts/contracts/bridgehub/L1MessageRoot.sol, l1-contracts/contracts/bridgehub/L2MessageRoot.sol, l1-contracts/contracts/bridgehub/MessageRootBase.sol, l1-contracts/contracts/upgrades/SettlementLayerV30Upgrade.sol, l1-contracts/deploy-scripts/upgrade/EcosystemUpgrade_v30.s.sol, l1-contracts/test/foundry/l1/integration/AssetTrackerTest.t.sol
=> remove redundunt assetMigrationNumber check

l1-contracts/contracts/common/Config.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Admin.sol
=> migration window check

l1-contracts/contracts/bridge/asset-tracker/AssetTrackerBase.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Admin.sol, l1-contracts/contracts/state-transition/chain-deps/facets/Mailbox.sol
=> chore: small fixes in kl/medium-interop

l1-contracts/contracts/bridge/L1Nullifier.sol, l1-contracts/contracts/bridgehub/L1MessageRoot.sol, l1-contracts/contracts/bridgehub/MessageRootBase.sol, l1-contracts/contracts/interop/InteropCenter.sol, l1-contracts/contracts/upgrades/SettlementLayerV30Upgrade.sol, system-contracts/bootloader/test_infra/Cargo.lock, system-contracts/bootloader/test_infra/Cargo.toml, system-contracts/bootloader/test_infra/src/main.rs, system-contracts/bootloader/tests/bootloader/bootloader_test.yul
=> Bundles CI fixes part II

system-contracts/README.md
We had a broken link in readme. It must be updated as a part of fixes to bring CI to green.
=> fix: fix broken link
